// Code generated by MockGen. DO NOT EDIT.
// Source: model.go
//
// Generated by this command:
//
//	mockgen -source=model.go -destination=mocks/model_repo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/matrixhub-ai/matrixhub/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIModelRepo is a mock of IModelRepo interface.
type MockIModelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIModelRepoMockRecorder
	isgomock struct{}
}

// MockIModelRepoMockRecorder is the mock recorder for MockIModelRepo.
type MockIModelRepoMockRecorder struct {
	mock *MockIModelRepo
}

// NewMockIModelRepo creates a new mock instance.
func NewMockIModelRepo(ctrl *gomock.Controller) *MockIModelRepo {
	mock := &MockIModelRepo{ctrl: ctrl}
	mock.recorder = &MockIModelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIModelRepo) EXPECT() *MockIModelRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockIModelRepo) Create(ctx context.Context, m *model.Model) (*model.Model, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(*model.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIModelRepoMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIModelRepo)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockIModelRepo) Delete(ctx context.Context, project, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, project, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIModelRepoMockRecorder) Delete(ctx, project, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIModelRepo)(nil).Delete), ctx, project, name)
}

// GetByProjectAndName mocks base method.
func (m *MockIModelRepo) GetByProjectAndName(ctx context.Context, project, name string) (*model.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectAndName", ctx, project, name)
	ret0, _ := ret[0].(*model.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectAndName indicates an expected call of GetByProjectAndName.
func (mr *MockIModelRepoMockRecorder) GetByProjectAndName(ctx, project, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectAndName", reflect.TypeOf((*MockIModelRepo)(nil).GetByProjectAndName), ctx, project, name)
}

// List mocks base method.
func (m *MockIModelRepo) List(ctx context.Context, filter *model.Filter) ([]*model.Model, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*model.Model)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIModelRepoMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIModelRepo)(nil).List), ctx, filter)
}

// ListAllPaths mocks base method.
func (m *MockIModelRepo) ListAllPaths(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPaths", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPaths indicates an expected call of ListAllPaths.
func (mr *MockIModelRepoMockRecorder) ListAllPaths(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPaths", reflect.TypeOf((*MockIModelRepo)(nil).ListAllPaths), ctx)
}

// UpdateMetadata mocks base method.
func (m *MockIModelRepo) UpdateMetadata(ctx context.Context, modelID int64, update *model.MetadataUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", ctx, modelID, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockIModelRepoMockRecorder) UpdateMetadata(ctx, modelID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockIModelRepo)(nil).UpdateMetadata), ctx, modelID, update)
}

// UpdateSetting mocks base method.
func (m *MockIModelRepo) UpdateSetting(ctx context.Context, modelID int64, update *model.SettingUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSetting", ctx, modelID, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSetting indicates an expected call of UpdateSetting.
func (mr *MockIModelRepoMockRecorder) UpdateSetting(ctx, modelID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSetting", reflect.TypeOf((*MockIModelRepo)(nil).UpdateSetting), ctx, modelID, update)
}

// MockILabelRepo is a mock of ILabelRepo interface.
type MockILabelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockILabelRepoMockRecorder
	isgomock struct{}
}

// MockILabelRepoMockRecorder is the mock recorder for MockILabelRepo.
type MockILabelRepoMockRecorder struct {
	mock *MockILabelRepo
}

// NewMockILabelRepo creates a new mock instance.
func NewMockILabelRepo(ctrl *gomock.Controller) *MockILabelRepo {
	mock := &MockILabelRepo{ctrl: ctrl}
	mock.recorder = &MockILabelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILabelRepo) EXPECT() *MockILabelRepoMockRecorder {
	return m.recorder
}

// GetByModelID mocks base method.
func (m *MockILabelRepo) GetByModelID(ctx context.Context, modelID int64) ([]*model.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByModelID", ctx, modelID)
	ret0, _ := ret[0].([]*model.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByModelID indicates an expected call of GetByModelID.
func (mr *MockILabelRepoMockRecorder) GetByModelID(ctx, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByModelID", reflect.TypeOf((*MockILabelRepo)(nil).GetByModelID), ctx, modelID)
}

// GetOrCreateByName mocks base method.
func (m *MockILabelRepo) GetOrCreateByName(ctx context.Context, name, category, scope string) (*model.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateByName", ctx, name, category, scope)
	ret0, _ := ret[0].(*model.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateByName indicates an expected call of GetOrCreateByName.
func (mr *MockILabelRepoMockRecorder) GetOrCreateByName(ctx, name, category, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateByName", reflect.TypeOf((*MockILabelRepo)(nil).GetOrCreateByName), ctx, name, category, scope)
}

// ListByCategoryAndScope mocks base method.
func (m *MockILabelRepo) ListByCategoryAndScope(ctx context.Context, category, scope string) ([]*model.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCategoryAndScope", ctx, category, scope)
	ret0, _ := ret[0].([]*model.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCategoryAndScope indicates an expected call of ListByCategoryAndScope.
func (mr *MockILabelRepoMockRecorder) ListByCategoryAndScope(ctx, category, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCategoryAndScope", reflect.TypeOf((*MockILabelRepo)(nil).ListByCategoryAndScope), ctx, category, scope)
}

// UpdateModelLabels mocks base method.
func (m *MockILabelRepo) UpdateModelLabels(ctx context.Context, modelID int64, labelIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModelLabels", ctx, modelID, labelIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateModelLabels indicates an expected call of UpdateModelLabels.
func (mr *MockILabelRepoMockRecorder) UpdateModelLabels(ctx, modelID, labelIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModelLabels", reflect.TypeOf((*MockILabelRepo)(nil).UpdateModelLabels), ctx, modelID, labelIDs)
}
