// Code generated by MockGen. DO NOT EDIT.
// Source: model_service.go
//
// Generated by this command:
//
//	mockgen -source=model_service.go -destination=mocks/model_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	git "github.com/matrixhub-ai/matrixhub/internal/domain/git"
	model "github.com/matrixhub-ai/matrixhub/internal/domain/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIModelService is a mock of IModelService interface.
type MockIModelService struct {
	ctrl     *gomock.Controller
	recorder *MockIModelServiceMockRecorder
	isgomock struct{}
}

// MockIModelServiceMockRecorder is the mock recorder for MockIModelService.
type MockIModelServiceMockRecorder struct {
	mock *MockIModelService
}

// NewMockIModelService creates a new mock instance.
func NewMockIModelService(ctrl *gomock.Controller) *MockIModelService {
	mock := &MockIModelService{ctrl: ctrl}
	mock.recorder = &MockIModelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIModelService) EXPECT() *MockIModelServiceMockRecorder {
	return m.recorder
}

// CheckOrSyncFromRemote mocks base method.
func (m *MockIModelService) CheckOrSyncFromRemote(ctx context.Context, project, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOrSyncFromRemote", ctx, project, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckOrSyncFromRemote indicates an expected call of CheckOrSyncFromRemote.
func (mr *MockIModelServiceMockRecorder) CheckOrSyncFromRemote(ctx, project, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOrSyncFromRemote", reflect.TypeOf((*MockIModelService)(nil).CheckOrSyncFromRemote), ctx, project, name)
}

// CreateModel mocks base method.
func (m *MockIModelService) CreateModel(ctx context.Context, project, name string) (*model.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModel", ctx, project, name)
	ret0, _ := ret[0].(*model.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModel indicates an expected call of CreateModel.
func (mr *MockIModelServiceMockRecorder) CreateModel(ctx, project, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModel", reflect.TypeOf((*MockIModelService)(nil).CreateModel), ctx, project, name)
}

// CreateModelCommit mocks base method.
func (m *MockIModelService) CreateModelCommit(ctx context.Context, project, name, revision string, commit *git.Commit, ops []git.CommitOperation) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModelCommit", ctx, project, name, revision, commit, ops)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModelCommit indicates an expected call of CreateModelCommit.
func (mr *MockIModelServiceMockRecorder) CreateModelCommit(ctx, project, name, revision, commit, ops any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModelCommit", reflect.TypeOf((*MockIModelService)(nil).CreateModelCommit), ctx, project, name, revision, commit, ops)
}

// DeleteModel mocks base method.
func (m *MockIModelService) DeleteModel(ctx context.Context, project, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModel", ctx, project, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModel indicates an expected call of DeleteModel.
func (mr *MockIModelServiceMockRecorder) DeleteModel(ctx, project, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModel", reflect.TypeOf((*MockIModelService)(nil).DeleteModel), ctx, project, name)
}

// EnsureModel mocks base method.
func (m *MockIModelService) EnsureModel(ctx context.Context, project, name string) (*model.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureModel", ctx, project, name)
	ret0, _ := ret[0].(*model.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureModel indicates an expected call of EnsureModel.
func (mr *MockIModelServiceMockRecorder) EnsureModel(ctx, project, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureModel", reflect.TypeOf((*MockIModelService)(nil).EnsureModel), ctx, project, name)
}

// GetModel mocks base method.
func (m *MockIModelService) GetModel(ctx context.Context, project, name string) (*model.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModel", ctx, project, name)
	ret0, _ := ret[0].(*model.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModel indicates an expected call of GetModel.
func (mr *MockIModelServiceMockRecorder) GetModel(ctx, project, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModel", reflect.TypeOf((*MockIModelService)(nil).GetModel), ctx, project, name)
}

// GetModelBlob mocks base method.
func (m *MockIModelService) GetModelBlob(ctx context.Context, project, name, revision, path string) (*git.TreeEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelBlob", ctx, project, name, revision, path)
	ret0, _ := ret[0].(*git.TreeEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelBlob indicates an expected call of GetModelBlob.
func (mr *MockIModelServiceMockRecorder) GetModelBlob(ctx, project, name, revision, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelBlob", reflect.TypeOf((*MockIModelService)(nil).GetModelBlob), ctx, project, name, revision, path)
}

// GetModelCommit mocks base method.
func (m *MockIModelService) GetModelCommit(ctx context.Context, project, name, commitID string) (*git.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelCommit", ctx, project, name, commitID)
	ret0, _ := ret[0].(*git.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelCommit indicates an expected call of GetModelCommit.
func (mr *MockIModelServiceMockRecorder) GetModelCommit(ctx, project, name, commitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelCommit", reflect.TypeOf((*MockIModelService)(nil).GetModelCommit), ctx, project, name, commitID)
}

// GetModelTree mocks base method.
func (m *MockIModelService) GetModelTree(ctx context.Context, project, name, revision, path string) ([]*git.TreeEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelTree", ctx, project, name, revision, path)
	ret0, _ := ret[0].([]*git.TreeEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelTree indicates an expected call of GetModelTree.
func (mr *MockIModelServiceMockRecorder) GetModelTree(ctx, project, name, revision, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelTree", reflect.TypeOf((*MockIModelService)(nil).GetModelTree), ctx, project, name, revision, path)
}

// ListModelCommits mocks base method.
func (m *MockIModelService) ListModelCommits(ctx context.Context, project, name, revision string, page, pageSize int) ([]*git.Commit, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelCommits", ctx, project, name, revision, page, pageSize)
	ret0, _ := ret[0].([]*git.Commit)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModelCommits indicates an expected call of ListModelCommits.
func (mr *MockIModelServiceMockRecorder) ListModelCommits(ctx, project, name, revision, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelCommits", reflect.TypeOf((*MockIModelService)(nil).ListModelCommits), ctx, project, name, revision, page, pageSize)
}

// ListModelFrameLabels mocks base method.
func (m *MockIModelService) ListModelFrameLabels(ctx context.Context) ([]*model.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelFrameLabels", ctx)
	ret0, _ := ret[0].([]*model.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelFrameLabels indicates an expected call of ListModelFrameLabels.
func (mr *MockIModelServiceMockRecorder) ListModelFrameLabels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelFrameLabels", reflect.TypeOf((*MockIModelService)(nil).ListModelFrameLabels), ctx)
}

// ListModelRevisions mocks base method.
func (m *MockIModelService) ListModelRevisions(ctx context.Context, project, name string) (*git.Revisions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelRevisions", ctx, project, name)
	ret0, _ := ret[0].(*git.Revisions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelRevisions indicates an expected call of ListModelRevisions.
func (mr *MockIModelServiceMockRecorder) ListModelRevisions(ctx, project, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelRevisions", reflect.TypeOf((*MockIModelService)(nil).ListModelRevisions), ctx, project, name)
}

// ListModelTaskLabels mocks base method.
func (m *MockIModelService) ListModelTaskLabels(ctx context.Context) ([]*model.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelTaskLabels", ctx)
	ret0, _ := ret[0].([]*model.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModelTaskLabels indicates an expected call of ListModelTaskLabels.
func (mr *MockIModelServiceMockRecorder) ListModelTaskLabels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelTaskLabels", reflect.TypeOf((*MockIModelService)(nil).ListModelTaskLabels), ctx)
}

// ListModels mocks base method.
func (m *MockIModelService) ListModels(ctx context.Context, filter *model.Filter) ([]*model.Model, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", ctx, filter)
	ret0, _ := ret[0].([]*model.Model)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModels indicates an expected call of ListModels.
func (mr *MockIModelServiceMockRecorder) ListModels(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockIModelService)(nil).ListModels), ctx, filter)
}

// SyncMetadata mocks base method.
func (m *MockIModelService) SyncMetadata(ctx context.Context, project, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncMetadata", ctx, project, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncMetadata indicates an expected call of SyncMetadata.
func (mr *MockIModelServiceMockRecorder) SyncMetadata(ctx, project, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncMetadata", reflect.TypeOf((*MockIModelService)(nil).SyncMetadata), ctx, project, name)
}

// UpdateModelSetting mocks base method.
func (m *MockIModelService) UpdateModelSetting(ctx context.Context, project, name string, update *model.SettingUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModelSetting", ctx, project, name, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateModelSetting indicates an expected call of UpdateModelSetting.
func (mr *MockIModelServiceMockRecorder) UpdateModelSetting(ctx, project, name, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModelSetting", reflect.TypeOf((*MockIModelService)(nil).UpdateModelSetting), ctx, project, name, update)
}
