/*
 * v1alpha1/project.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

import (
	"time"
)

type V1alpha1Project struct {
	Name string `json:"name,omitempty"`
	Type_ *V1alpha1ProjectType `json:"type,omitempty"`
	EnabledRegistry bool `json:"enabledRegistry,omitempty"`
	ModelCount int64 `json:"modelCount,omitempty"`
	DatasetCount int64 `json:"datasetCount,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
