/*
 * v1alpha1/project.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1MemberType string

// List of v1alpha1MemberType
const (
	USER_V1alpha1MemberType V1alpha1MemberType = "MEMBER_TYPE_USER"
	GROUP_V1alpha1MemberType V1alpha1MemberType = "MEMBER_TYPE_GROUP"
)
