/*
 * v1alpha1/project.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1CreateProjectRequest struct {
	Name string `json:"name,omitempty"`
	Type_ *V1alpha1ProjectType `json:"type,omitempty"`
	RegistryId int32 `json:"registryId,omitempty"`
	Organization string `json:"organization,omitempty"`
}
