/*
 * v1alpha1/project.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1ProjectType string

// List of v1alpha1ProjectType
const (
	UNSPECIFIED_V1alpha1ProjectType V1alpha1ProjectType = "PROJECT_TYPE_UNSPECIFIED"
	PRIVATE_V1alpha1ProjectType V1alpha1ProjectType = "PROJECT_TYPE_PRIVATE"
	PUBLIC_V1alpha1ProjectType V1alpha1ProjectType = "PROJECT_TYPE_PUBLIC"
)
