# golangci-lint configuration file
# see: https://golangci-lint.run/usage/configuration/

version: "2"
linters:
  enable:
    # - copyloopvar
    # - dupword
    # - durationcheck
    # - fatcontext
    # - ginkgolinter
    - gocritic
    - goheader
    - intrange
    # - loggercheck
    - makezero
    - misspell
    # - modernize
    # - nilerr
    # - nilnesserr
    # - nolintlint
    # - perfsprint
    # - revive
    # - unconvert
    # - forbidigo
  settings:
    gocritic:
      enabled-checks:
        - dupImport
        - stringsCompare
      disabled-checks:
        - appendAssign
        - exitAfterDefer
    goheader:
      template: |-
        Copyright The MatrixHub Authors.

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
issues:
  # Show all issues from a linter
  max-issues-per-linter: 0
  # Show all issues with the same text
  max-same-issues: 0
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/matrixhub-ai/matrixhub) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports.
  exclusions:
    generated: lax
    paths:
      - vendor
