/*
 * v1alpha1/cleanup.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

// Storage by kind; not an atomic snapshot.
type V1alpha1StorageStats struct {
	TotalSizeBytes string `json:"totalSizeBytes,omitempty"`
	Git *V1alpha1GitStorageUsage `json:"git,omitempty"`
	Xet *V1alpha1XetStorageUsage `json:"xet,omitempty"`
}
