/*
 * v1alpha1/cleanup.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1XetStorageUsage struct {
	Xorbs *V1alpha1StorageObjectUsage `json:"xorbs,omitempty"`
	Shards *V1alpha1StorageObjectUsage `json:"shards,omitempty"`
	FileIndex *V1alpha1StorageObjectUsage `json:"fileIndex,omitempty"`
	ChunkIndex *V1alpha1StorageObjectUsage `json:"chunkIndex,omitempty"`
	Sha256Index *V1alpha1StorageObjectUsage `json:"sha256Index,omitempty"`
}
