/*
 * v1alpha1/cleanup.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

// Every repository under the repositories root; unreachable objects included, LFS content excluded.
type V1alpha1GitStorageUsage struct {
	Objects *V1alpha1StorageObjectUsage `json:"objects,omitempty"`
	Other *V1alpha1StorageObjectUsage `json:"other,omitempty"`
}
