/*
 * v1alpha1/current_user.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1ProjectRoleType string

// List of v1alpha1ProjectRoleType
const (
	ADMIN_V1alpha1ProjectRoleType V1alpha1ProjectRoleType = "ROLE_TYPE_PROJECT_ADMIN"
	EDITOR_V1alpha1ProjectRoleType V1alpha1ProjectRoleType = "ROLE_TYPE_PROJECT_EDITOR"
	VIEWER_V1alpha1ProjectRoleType V1alpha1ProjectRoleType = "ROLE_TYPE_PROJECT_VIEWER"
)
