/*
 * v1alpha1/current_user.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1GetCurrentUserResponse struct {
	Id int64 `json:"id,omitempty"`
	Username string `json:"username,omitempty"`
	IsAdmin bool `json:"isAdmin,omitempty"`
}
