apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrixhub.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrixhub.labels" . | nindent 4 }}
type: Opaque
data:
  matrixhub.dsn: {{ include "matrixhub.database.dsn" . | b64enc | quote }}
