// Code generated by MockGen. DO NOT EDIT.
// Source: sync_job_service.go
//
// Generated by this command:
//
//	mockgen -source=sync_job_service.go -destination=mocks/sync_job_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	job "github.com/matrixhub-ai/matrixhub/internal/domain/job"
	syncjob "github.com/matrixhub-ai/matrixhub/internal/domain/syncjob"
	gomock "go.uber.org/mock/gomock"
)

// MockISyncJobService is a mock of ISyncJobService interface.
type MockISyncJobService struct {
	ctrl     *gomock.Controller
	recorder *MockISyncJobServiceMockRecorder
	isgomock struct{}
}

// MockISyncJobServiceMockRecorder is the mock recorder for MockISyncJobService.
type MockISyncJobServiceMockRecorder struct {
	mock *MockISyncJobService
}

// NewMockISyncJobService creates a new mock instance.
func NewMockISyncJobService(ctrl *gomock.Controller) *MockISyncJobService {
	mock := &MockISyncJobService{ctrl: ctrl}
	mock.recorder = &MockISyncJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISyncJobService) EXPECT() *MockISyncJobServiceMockRecorder {
	return m.recorder
}

// ClaimPendingSyncJobs mocks base method.
func (m *MockISyncJobService) ClaimPendingSyncJobs(ctx context.Context, nowMs int64) ([]job.DueJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingSyncJobs", ctx, nowMs)
	ret0, _ := ret[0].([]job.DueJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingSyncJobs indicates an expected call of ClaimPendingSyncJobs.
func (mr *MockISyncJobServiceMockRecorder) ClaimPendingSyncJobs(ctx, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingSyncJobs", reflect.TypeOf((*MockISyncJobService)(nil).ClaimPendingSyncJobs), ctx, nowMs)
}

// CreateSyncJob mocks base method.
func (m *MockISyncJobService) CreateSyncJob(ctx context.Context, param *syncjob.SyncJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncJob", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSyncJob indicates an expected call of CreateSyncJob.
func (mr *MockISyncJobServiceMockRecorder) CreateSyncJob(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncJob", reflect.TypeOf((*MockISyncJobService)(nil).CreateSyncJob), ctx, param)
}

// ExecuteSyncJob mocks base method.
func (m *MockISyncJobService) ExecuteSyncJob(ctx context.Context, param *syncjob.SyncJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteSyncJob", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteSyncJob indicates an expected call of ExecuteSyncJob.
func (mr *MockISyncJobServiceMockRecorder) ExecuteSyncJob(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteSyncJob", reflect.TypeOf((*MockISyncJobService)(nil).ExecuteSyncJob), ctx, param)
}

// ExecuteSyncJobWithLog mocks base method.
func (m *MockISyncJobService) ExecuteSyncJobWithLog(ctx context.Context, jobID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteSyncJobWithLog", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteSyncJobWithLog indicates an expected call of ExecuteSyncJobWithLog.
func (mr *MockISyncJobServiceMockRecorder) ExecuteSyncJobWithLog(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteSyncJobWithLog", reflect.TypeOf((*MockISyncJobService)(nil).ExecuteSyncJobWithLog), ctx, jobID)
}

// GetSyncJob mocks base method.
func (m *MockISyncJobService) GetSyncJob(ctx context.Context, id int) (*syncjob.SyncJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncJob", ctx, id)
	ret0, _ := ret[0].(*syncjob.SyncJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncJob indicates an expected call of GetSyncJob.
func (mr *MockISyncJobServiceMockRecorder) GetSyncJob(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncJob", reflect.TypeOf((*MockISyncJobService)(nil).GetSyncJob), ctx, id)
}

// ListSyncJobsByTaskID mocks base method.
func (m *MockISyncJobService) ListSyncJobsByTaskID(ctx context.Context, taskID, page, pageSize int, status syncjob.SyncJobStatus, resourceType string) ([]*syncjob.SyncJob, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSyncJobsByTaskID", ctx, taskID, page, pageSize, status, resourceType)
	ret0, _ := ret[0].([]*syncjob.SyncJob)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSyncJobsByTaskID indicates an expected call of ListSyncJobsByTaskID.
func (mr *MockISyncJobServiceMockRecorder) ListSyncJobsByTaskID(ctx, taskID, page, pageSize, status, resourceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSyncJobsByTaskID", reflect.TypeOf((*MockISyncJobService)(nil).ListSyncJobsByTaskID), ctx, taskID, page, pageSize, status, resourceType)
}

// SetOnJobDone mocks base method.
func (m *MockISyncJobService) SetOnJobDone(fn func(context.Context, int) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnJobDone", fn)
}

// SetOnJobDone indicates an expected call of SetOnJobDone.
func (mr *MockISyncJobServiceMockRecorder) SetOnJobDone(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnJobDone", reflect.TypeOf((*MockISyncJobService)(nil).SetOnJobDone), fn)
}

// UpdateSyncJob mocks base method.
func (m *MockISyncJobService) UpdateSyncJob(ctx context.Context, param *syncjob.SyncJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncJob", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncJob indicates an expected call of UpdateSyncJob.
func (mr *MockISyncJobServiceMockRecorder) UpdateSyncJob(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncJob", reflect.TypeOf((*MockISyncJobService)(nil).UpdateSyncJob), ctx, param)
}

// MockLogStore is a mock of LogStore interface.
type MockLogStore struct {
	ctrl     *gomock.Controller
	recorder *MockLogStoreMockRecorder
	isgomock struct{}
}

// MockLogStoreMockRecorder is the mock recorder for MockLogStore.
type MockLogStoreMockRecorder struct {
	mock *MockLogStore
}

// NewMockLogStore creates a new mock instance.
func NewMockLogStore(ctrl *gomock.Controller) *MockLogStore {
	mock := &MockLogStore{ctrl: ctrl}
	mock.recorder = &MockLogStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogStore) EXPECT() *MockLogStoreMockRecorder {
	return m.recorder
}

// Reader mocks base method.
func (m *MockLogStore) Reader(jobID int) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reader", jobID)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reader indicates an expected call of Reader.
func (mr *MockLogStoreMockRecorder) Reader(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reader", reflect.TypeOf((*MockLogStore)(nil).Reader), jobID)
}

// Writer mocks base method.
func (m *MockLogStore) Writer(jobID int) (io.WriteCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Writer", jobID)
	ret0, _ := ret[0].(io.WriteCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Writer indicates an expected call of Writer.
func (mr *MockLogStoreMockRecorder) Writer(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Writer", reflect.TypeOf((*MockLogStore)(nil).Writer), jobID)
}
