/*
 * v1alpha1/sync_policy.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1SyncPolicyType string

// List of v1alpha1SyncPolicyType
const (
	UNSPECIFIED_V1alpha1SyncPolicyType V1alpha1SyncPolicyType = "SYNC_POLICY_TYPE_UNSPECIFIED"
	PULL_BASE_V1alpha1SyncPolicyType V1alpha1SyncPolicyType = "SYNC_POLICY_TYPE_PULL_BASE"
	PUSH_BASE_V1alpha1SyncPolicyType V1alpha1SyncPolicyType = "SYNC_POLICY_TYPE_PUSH_BASE"
)
