/*
 * v1alpha1/model.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1FileType string

// List of v1alpha1FileType
const (
	DIR_V1alpha1FileType V1alpha1FileType = "DIR"
	FILE_V1alpha1FileType V1alpha1FileType = "FILE"
)
