/*
 * v1alpha1/model.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type MatrixhubV1alpha1Label struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Category *V1alpha1Category `json:"category,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
}
