/*
 * v1alpha1/model.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1Revisions struct {
	Branches []V1alpha1Revision `json:"branches,omitempty"`
	Tags []V1alpha1Revision `json:"tags,omitempty"`
}
