/*
 * v1alpha1/model.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1Category string

// List of v1alpha1Category
const (
	TASK_V1alpha1Category V1alpha1Category = "TASK"
	LIBRARY_V1alpha1Category V1alpha1Category = "LIBRARY"
	LICENSE_V1alpha1Category V1alpha1Category = "LICENSE"
	LANGUAGE_V1alpha1Category V1alpha1Category = "LANGUAGE"
	OTHER_V1alpha1Category V1alpha1Category = "OTHER"
)
