// Code generated by MockGen. DO NOT EDIT.
// Source: generator.go
//
// Generated by this command:
//
//	mockgen -source=generator.go -destination=mocks/generator_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	syncjob "github.com/matrixhub-ai/matrixhub/internal/domain/syncjob"
	syncpolicy "github.com/matrixhub-ai/matrixhub/internal/domain/syncpolicy"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncJobGenerator is a mock of SyncJobGenerator interface.
type MockSyncJobGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSyncJobGeneratorMockRecorder
	isgomock struct{}
}

// MockSyncJobGeneratorMockRecorder is the mock recorder for MockSyncJobGenerator.
type MockSyncJobGeneratorMockRecorder struct {
	mock *MockSyncJobGenerator
}

// NewMockSyncJobGenerator creates a new mock instance.
func NewMockSyncJobGenerator(ctrl *gomock.Controller) *MockSyncJobGenerator {
	mock := &MockSyncJobGenerator{ctrl: ctrl}
	mock.recorder = &MockSyncJobGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncJobGenerator) EXPECT() *MockSyncJobGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockSyncJobGenerator) Generate(ctx context.Context, policy *syncpolicy.SyncPolicy) (*syncpolicy.SyncTask, []*syncjob.SyncJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, policy)
	ret0, _ := ret[0].(*syncpolicy.SyncTask)
	ret1, _ := ret[1].([]*syncjob.SyncJob)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Generate indicates an expected call of Generate.
func (mr *MockSyncJobGeneratorMockRecorder) Generate(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockSyncJobGenerator)(nil).Generate), ctx, policy)
}
