// Code generated by MockGen. DO NOT EDIT.
// Source: sync_policy_service.go
//
// Generated by this command:
//
//	mockgen -source=sync_policy_service.go -destination=mocks/sync_policy_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	job "github.com/matrixhub-ai/matrixhub/internal/domain/job"
	syncpolicy "github.com/matrixhub-ai/matrixhub/internal/domain/syncpolicy"
	gomock "go.uber.org/mock/gomock"
)

// MockISyncPolicyService is a mock of ISyncPolicyService interface.
type MockISyncPolicyService struct {
	ctrl     *gomock.Controller
	recorder *MockISyncPolicyServiceMockRecorder
	isgomock struct{}
}

// MockISyncPolicyServiceMockRecorder is the mock recorder for MockISyncPolicyService.
type MockISyncPolicyServiceMockRecorder struct {
	mock *MockISyncPolicyService
}

// NewMockISyncPolicyService creates a new mock instance.
func NewMockISyncPolicyService(ctrl *gomock.Controller) *MockISyncPolicyService {
	mock := &MockISyncPolicyService{ctrl: ctrl}
	mock.recorder = &MockISyncPolicyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISyncPolicyService) EXPECT() *MockISyncPolicyServiceMockRecorder {
	return m.recorder
}

// ClaimDueSyncPolicies mocks base method.
func (m *MockISyncPolicyService) ClaimDueSyncPolicies(ctx context.Context, nowMs int64) ([]job.DueJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDueSyncPolicies", ctx, nowMs)
	ret0, _ := ret[0].([]job.DueJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDueSyncPolicies indicates an expected call of ClaimDueSyncPolicies.
func (mr *MockISyncPolicyServiceMockRecorder) ClaimDueSyncPolicies(ctx, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDueSyncPolicies", reflect.TypeOf((*MockISyncPolicyService)(nil).ClaimDueSyncPolicies), ctx, nowMs)
}

// ClaimPendingSyncTasks mocks base method.
func (m *MockISyncPolicyService) ClaimPendingSyncTasks(ctx context.Context, nowMs int64) ([]job.DueJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingSyncTasks", ctx, nowMs)
	ret0, _ := ret[0].([]job.DueJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingSyncTasks indicates an expected call of ClaimPendingSyncTasks.
func (mr *MockISyncPolicyServiceMockRecorder) ClaimPendingSyncTasks(ctx, nowMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingSyncTasks", reflect.TypeOf((*MockISyncPolicyService)(nil).ClaimPendingSyncTasks), ctx, nowMs)
}

// CreatePendingSyncTask mocks base method.
func (m *MockISyncPolicyService) CreatePendingSyncTask(ctx context.Context, policyID, triggerType int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePendingSyncTask", ctx, policyID, triggerType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePendingSyncTask indicates an expected call of CreatePendingSyncTask.
func (mr *MockISyncPolicyServiceMockRecorder) CreatePendingSyncTask(ctx, policyID, triggerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePendingSyncTask", reflect.TypeOf((*MockISyncPolicyService)(nil).CreatePendingSyncTask), ctx, policyID, triggerType)
}

// CreateSyncPolicy mocks base method.
func (m *MockISyncPolicyService) CreateSyncPolicy(ctx context.Context, param *syncpolicy.SyncPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncPolicy", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSyncPolicy indicates an expected call of CreateSyncPolicy.
func (mr *MockISyncPolicyServiceMockRecorder) CreateSyncPolicy(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncPolicy", reflect.TypeOf((*MockISyncPolicyService)(nil).CreateSyncPolicy), ctx, param)
}

// CreateSyncTask mocks base method.
func (m *MockISyncPolicyService) CreateSyncTask(ctx context.Context, param *syncpolicy.SyncTask) (*syncpolicy.SyncTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncTask", ctx, param)
	ret0, _ := ret[0].(*syncpolicy.SyncTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSyncTask indicates an expected call of CreateSyncTask.
func (mr *MockISyncPolicyServiceMockRecorder) CreateSyncTask(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncTask", reflect.TypeOf((*MockISyncPolicyService)(nil).CreateSyncTask), ctx, param)
}

// CreateSyncTaskAndSyncJobs mocks base method.
func (m *MockISyncPolicyService) CreateSyncTaskAndSyncJobs(ctx context.Context, policy *syncpolicy.SyncPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncTaskAndSyncJobs", ctx, policy)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSyncTaskAndSyncJobs indicates an expected call of CreateSyncTaskAndSyncJobs.
func (mr *MockISyncPolicyServiceMockRecorder) CreateSyncTaskAndSyncJobs(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncTaskAndSyncJobs", reflect.TypeOf((*MockISyncPolicyService)(nil).CreateSyncTaskAndSyncJobs), ctx, policy)
}

// CreateSyncTaskAsync mocks base method.
func (m *MockISyncPolicyService) CreateSyncTaskAsync(ctx context.Context, policy *syncpolicy.SyncPolicy) (*syncpolicy.SyncTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncTaskAsync", ctx, policy)
	ret0, _ := ret[0].(*syncpolicy.SyncTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSyncTaskAsync indicates an expected call of CreateSyncTaskAsync.
func (mr *MockISyncPolicyServiceMockRecorder) CreateSyncTaskAsync(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncTaskAsync", reflect.TypeOf((*MockISyncPolicyService)(nil).CreateSyncTaskAsync), ctx, policy)
}

// DeleteSyncPolicy mocks base method.
func (m *MockISyncPolicyService) DeleteSyncPolicy(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSyncPolicy", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSyncPolicy indicates an expected call of DeleteSyncPolicy.
func (mr *MockISyncPolicyServiceMockRecorder) DeleteSyncPolicy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSyncPolicy", reflect.TypeOf((*MockISyncPolicyService)(nil).DeleteSyncPolicy), ctx, id)
}

// ExecuteSyncTask mocks base method.
func (m *MockISyncPolicyService) ExecuteSyncTask(ctx context.Context, taskID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteSyncTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteSyncTask indicates an expected call of ExecuteSyncTask.
func (mr *MockISyncPolicyServiceMockRecorder) ExecuteSyncTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteSyncTask", reflect.TypeOf((*MockISyncPolicyService)(nil).ExecuteSyncTask), ctx, taskID)
}

// GetSyncPolicy mocks base method.
func (m *MockISyncPolicyService) GetSyncPolicy(ctx context.Context, id int) (*syncpolicy.SyncPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncPolicy", ctx, id)
	ret0, _ := ret[0].(*syncpolicy.SyncPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncPolicy indicates an expected call of GetSyncPolicy.
func (mr *MockISyncPolicyServiceMockRecorder) GetSyncPolicy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncPolicy", reflect.TypeOf((*MockISyncPolicyService)(nil).GetSyncPolicy), ctx, id)
}

// GetSyncTask mocks base method.
func (m *MockISyncPolicyService) GetSyncTask(ctx context.Context, id int) (*syncpolicy.SyncTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncTask", ctx, id)
	ret0, _ := ret[0].(*syncpolicy.SyncTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncTask indicates an expected call of GetSyncTask.
func (mr *MockISyncPolicyServiceMockRecorder) GetSyncTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncTask", reflect.TypeOf((*MockISyncPolicyService)(nil).GetSyncTask), ctx, id)
}

// ListSyncPolicies mocks base method.
func (m *MockISyncPolicyService) ListSyncPolicies(ctx context.Context, page, pageSize int, search string) ([]*syncpolicy.SyncPolicy, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSyncPolicies", ctx, page, pageSize, search)
	ret0, _ := ret[0].([]*syncpolicy.SyncPolicy)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSyncPolicies indicates an expected call of ListSyncPolicies.
func (mr *MockISyncPolicyServiceMockRecorder) ListSyncPolicies(ctx, page, pageSize, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSyncPolicies", reflect.TypeOf((*MockISyncPolicyService)(nil).ListSyncPolicies), ctx, page, pageSize, search)
}

// ListSyncTasksByPolicyID mocks base method.
func (m *MockISyncPolicyService) ListSyncTasksByPolicyID(ctx context.Context, policyID, page, pageSize int, status syncpolicy.SyncTaskStatus) ([]*syncpolicy.SyncTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSyncTasksByPolicyID", ctx, policyID, page, pageSize, status)
	ret0, _ := ret[0].([]*syncpolicy.SyncTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSyncTasksByPolicyID indicates an expected call of ListSyncTasksByPolicyID.
func (mr *MockISyncPolicyServiceMockRecorder) ListSyncTasksByPolicyID(ctx, policyID, page, pageSize, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSyncTasksByPolicyID", reflect.TypeOf((*MockISyncPolicyService)(nil).ListSyncTasksByPolicyID), ctx, policyID, page, pageSize, status)
}

// ReportTaskStatus mocks base method.
func (m *MockISyncPolicyService) ReportTaskStatus(ctx context.Context, taskID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportTaskStatus", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportTaskStatus indicates an expected call of ReportTaskStatus.
func (mr *MockISyncPolicyServiceMockRecorder) ReportTaskStatus(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportTaskStatus", reflect.TypeOf((*MockISyncPolicyService)(nil).ReportTaskStatus), ctx, taskID)
}

// UpdateSyncPolicy mocks base method.
func (m *MockISyncPolicyService) UpdateSyncPolicy(ctx context.Context, param *syncpolicy.SyncPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncPolicy", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncPolicy indicates an expected call of UpdateSyncPolicy.
func (mr *MockISyncPolicyServiceMockRecorder) UpdateSyncPolicy(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncPolicy", reflect.TypeOf((*MockISyncPolicyService)(nil).UpdateSyncPolicy), ctx, param)
}

// UpdateSyncTask mocks base method.
func (m *MockISyncPolicyService) UpdateSyncTask(ctx context.Context, param *syncpolicy.SyncTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncTask", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncTask indicates an expected call of UpdateSyncTask.
func (mr *MockISyncPolicyServiceMockRecorder) UpdateSyncTask(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncTask", reflect.TypeOf((*MockISyncPolicyService)(nil).UpdateSyncTask), ctx, param)
}
