// Code generated by MockGen. DO NOT EDIT.
// Source: sync_task.go
//
// Generated by this command:
//
//	mockgen -source=sync_task.go -destination=mocks/sync_task_repo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	syncpolicy "github.com/matrixhub-ai/matrixhub/internal/domain/syncpolicy"
	gomock "go.uber.org/mock/gomock"
)

// MockISyncTaskRepo is a mock of ISyncTaskRepo interface.
type MockISyncTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockISyncTaskRepoMockRecorder
	isgomock struct{}
}

// MockISyncTaskRepoMockRecorder is the mock recorder for MockISyncTaskRepo.
type MockISyncTaskRepoMockRecorder struct {
	mock *MockISyncTaskRepo
}

// NewMockISyncTaskRepo creates a new mock instance.
func NewMockISyncTaskRepo(ctrl *gomock.Controller) *MockISyncTaskRepo {
	mock := &MockISyncTaskRepo{ctrl: ctrl}
	mock.recorder = &MockISyncTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISyncTaskRepo) EXPECT() *MockISyncTaskRepoMockRecorder {
	return m.recorder
}

// CreateSyncTask mocks base method.
func (m *MockISyncTaskRepo) CreateSyncTask(ctx context.Context, task *syncpolicy.SyncTask) (*syncpolicy.SyncTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncTask", ctx, task)
	ret0, _ := ret[0].(*syncpolicy.SyncTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSyncTask indicates an expected call of CreateSyncTask.
func (mr *MockISyncTaskRepoMockRecorder) CreateSyncTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncTask", reflect.TypeOf((*MockISyncTaskRepo)(nil).CreateSyncTask), ctx, task)
}

// DeleteSyncTask mocks base method.
func (m *MockISyncTaskRepo) DeleteSyncTask(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSyncTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSyncTask indicates an expected call of DeleteSyncTask.
func (mr *MockISyncTaskRepoMockRecorder) DeleteSyncTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSyncTask", reflect.TypeOf((*MockISyncTaskRepo)(nil).DeleteSyncTask), ctx, id)
}

// GetSyncTask mocks base method.
func (m *MockISyncTaskRepo) GetSyncTask(ctx context.Context, id int) (*syncpolicy.SyncTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncTask", ctx, id)
	ret0, _ := ret[0].(*syncpolicy.SyncTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncTask indicates an expected call of GetSyncTask.
func (mr *MockISyncTaskRepoMockRecorder) GetSyncTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncTask", reflect.TypeOf((*MockISyncTaskRepo)(nil).GetSyncTask), ctx, id)
}

// ListSyncTasksByPolicyID mocks base method.
func (m *MockISyncTaskRepo) ListSyncTasksByPolicyID(ctx context.Context, policyID, page, pageSize int, status syncpolicy.SyncTaskStatus) ([]*syncpolicy.SyncTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSyncTasksByPolicyID", ctx, policyID, page, pageSize, status)
	ret0, _ := ret[0].([]*syncpolicy.SyncTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSyncTasksByPolicyID indicates an expected call of ListSyncTasksByPolicyID.
func (mr *MockISyncTaskRepoMockRecorder) ListSyncTasksByPolicyID(ctx, policyID, page, pageSize, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSyncTasksByPolicyID", reflect.TypeOf((*MockISyncTaskRepo)(nil).ListSyncTasksByPolicyID), ctx, policyID, page, pageSize, status)
}

// SelectPendingTasks mocks base method.
func (m *MockISyncTaskRepo) SelectPendingTasks(ctx context.Context, limit int) ([]*syncpolicy.SyncTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPendingTasks", ctx, limit)
	ret0, _ := ret[0].([]*syncpolicy.SyncTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPendingTasks indicates an expected call of SelectPendingTasks.
func (mr *MockISyncTaskRepoMockRecorder) SelectPendingTasks(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPendingTasks", reflect.TypeOf((*MockISyncTaskRepo)(nil).SelectPendingTasks), ctx, limit)
}

// UpdateSyncTask mocks base method.
func (m *MockISyncTaskRepo) UpdateSyncTask(ctx context.Context, task *syncpolicy.SyncTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncTask indicates an expected call of UpdateSyncTask.
func (mr *MockISyncTaskRepoMockRecorder) UpdateSyncTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncTask", reflect.TypeOf((*MockISyncTaskRepo)(nil).UpdateSyncTask), ctx, task)
}

// UpdateTaskStatusCAS mocks base method.
func (m *MockISyncTaskRepo) UpdateTaskStatusCAS(ctx context.Context, taskID int, fromStatus, toStatus syncpolicy.SyncTaskStatus) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatusCAS", ctx, taskID, fromStatus, toStatus)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatusCAS indicates an expected call of UpdateTaskStatusCAS.
func (mr *MockISyncTaskRepoMockRecorder) UpdateTaskStatusCAS(ctx, taskID, fromStatus, toStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatusCAS", reflect.TypeOf((*MockISyncTaskRepo)(nil).UpdateTaskStatusCAS), ctx, taskID, fromStatus, toStatus)
}
