/*
 * v1alpha1/user.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

import (
	"time"
)

type V1alpha1GetUserResponse struct {
	Id int64 `json:"id,omitempty"`
	Username string `json:"username,omitempty"`
	Email string `json:"email,omitempty"`
	IsAdmin bool `json:"isAdmin,omitempty"`
	Source *V1alpha1UserSource `json:"source,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
}
