/*
 * v1alpha1/user.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1UserSource string

// List of v1alpha1UserSource
const (
	UNSPECIFIED_V1alpha1UserSource V1alpha1UserSource = "USER_SOURCE_UNSPECIFIED"
	LOCAL_V1alpha1UserSource V1alpha1UserSource = "USER_SOURCE_LOCAL"
)
