/*
 * v1alpha1/user.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1ListUsersResponse struct {
	Users []V1alpha1User `json:"users,omitempty"`
	Pagination *V1alpha1Pagination `json:"pagination,omitempty"`
}
