// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/abc.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetAbcRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetAbcRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAbcRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetAbcRequestMultiError, or
// nil if none found.
func (m *GetAbcRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAbcRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return GetAbcRequestMultiError(errors)
	}

	return nil
}

// GetAbcRequestMultiError is an error wrapping multiple validation errors
// returned by GetAbcRequest.ValidateAll() if the designated constraints
// aren't met.
type GetAbcRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAbcRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAbcRequestMultiError) AllErrors() []error { return m }

// GetAbcRequestValidationError is the validation error returned by
// GetAbcRequest.Validate if the designated constraints aren't met.
type GetAbcRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAbcRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAbcRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAbcRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAbcRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAbcRequestValidationError) ErrorName() string { return "GetAbcRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetAbcRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAbcRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAbcRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAbcRequestValidationError{}

// Validate checks the field values on GetAbcResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetAbcResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAbcResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetAbcResponseMultiError,
// or nil if none found.
func (m *GetAbcResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAbcResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return GetAbcResponseMultiError(errors)
	}

	return nil
}

// GetAbcResponseMultiError is an error wrapping multiple validation errors
// returned by GetAbcResponse.ValidateAll() if the designated constraints
// aren't met.
type GetAbcResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAbcResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAbcResponseMultiError) AllErrors() []error { return m }

// GetAbcResponseValidationError is the validation error returned by
// GetAbcResponse.Validate if the designated constraints aren't met.
type GetAbcResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAbcResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAbcResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAbcResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAbcResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAbcResponseValidationError) ErrorName() string { return "GetAbcResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetAbcResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAbcResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAbcResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAbcResponseValidationError{}
