// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/abc.proto

package v1alpha1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAbcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbcRequest) Reset() {
	*x = GetAbcRequest{}
	mi := &file_v1alpha1_abc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbcRequest) ProtoMessage() {}

func (x *GetAbcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_abc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbcRequest.ProtoReflect.Descriptor instead.
func (*GetAbcRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_abc_proto_rawDescGZIP(), []int{0}
}

func (x *GetAbcRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAbcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbcResponse) Reset() {
	*x = GetAbcResponse{}
	mi := &file_v1alpha1_abc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbcResponse) ProtoMessage() {}

func (x *GetAbcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_abc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbcResponse.ProtoReflect.Descriptor instead.
func (*GetAbcResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_abc_proto_rawDescGZIP(), []int{1}
}

func (x *GetAbcResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_v1alpha1_abc_proto protoreflect.FileDescriptor

const file_v1alpha1_abc_proto_rawDesc = "" +
	"\n" +
	"\x12v1alpha1/abc.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"#\n" +
	"\rGetAbcRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\x0eGetAbcResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2y\n" +
	"\x04Abcs\x12q\n" +
	"\x06GetAbc\x12!.matrixhub.v1alpha1.GetAbcRequest\x1a\".matrixhub.v1alpha1.GetAbcResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1alpha1/abc/{name}B<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_abc_proto_rawDescOnce sync.Once
	file_v1alpha1_abc_proto_rawDescData []byte
)

func file_v1alpha1_abc_proto_rawDescGZIP() []byte {
	file_v1alpha1_abc_proto_rawDescOnce.Do(func() {
		file_v1alpha1_abc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_abc_proto_rawDesc), len(file_v1alpha1_abc_proto_rawDesc)))
	})
	return file_v1alpha1_abc_proto_rawDescData
}

var file_v1alpha1_abc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1alpha1_abc_proto_goTypes = []any{
	(*GetAbcRequest)(nil),  // 0: matrixhub.v1alpha1.GetAbcRequest
	(*GetAbcResponse)(nil), // 1: matrixhub.v1alpha1.GetAbcResponse
}
var file_v1alpha1_abc_proto_depIdxs = []int32{
	0, // 0: matrixhub.v1alpha1.Abcs.GetAbc:input_type -> matrixhub.v1alpha1.GetAbcRequest
	1, // 1: matrixhub.v1alpha1.Abcs.GetAbc:output_type -> matrixhub.v1alpha1.GetAbcResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1alpha1_abc_proto_init() }
func file_v1alpha1_abc_proto_init() {
	if File_v1alpha1_abc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_abc_proto_rawDesc), len(file_v1alpha1_abc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_abc_proto_goTypes,
		DependencyIndexes: file_v1alpha1_abc_proto_depIdxs,
		MessageInfos:      file_v1alpha1_abc_proto_msgTypes,
	}.Build()
	File_v1alpha1_abc_proto = out.File
	file_v1alpha1_abc_proto_goTypes = nil
	file_v1alpha1_abc_proto_depIdxs = nil
}
