// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: v1alpha1/abc.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Abcs_GetAbc_FullMethodName = "/matrixhub.v1alpha1.Abcs/GetAbc"
)

// AbcsClient is the client API for Abcs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AbcsClient interface {
	GetAbc(ctx context.Context, in *GetAbcRequest, opts ...grpc.CallOption) (*GetAbcResponse, error)
}

type abcsClient struct {
	cc grpc.ClientConnInterface
}

func NewAbcsClient(cc grpc.ClientConnInterface) AbcsClient {
	return &abcsClient{cc}
}

func (c *abcsClient) GetAbc(ctx context.Context, in *GetAbcRequest, opts ...grpc.CallOption) (*GetAbcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAbcResponse)
	err := c.cc.Invoke(ctx, Abcs_GetAbc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AbcsServer is the server API for Abcs service.
// All implementations should embed UnimplementedAbcsServer
// for forward compatibility.
type AbcsServer interface {
	GetAbc(context.Context, *GetAbcRequest) (*GetAbcResponse, error)
}

// UnimplementedAbcsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAbcsServer struct{}

func (UnimplementedAbcsServer) GetAbc(context.Context, *GetAbcRequest) (*GetAbcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAbc not implemented")
}
func (UnimplementedAbcsServer) testEmbeddedByValue() {}

// UnsafeAbcsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AbcsServer will
// result in compilation errors.
type UnsafeAbcsServer interface {
	mustEmbedUnimplementedAbcsServer()
}

func RegisterAbcsServer(s grpc.ServiceRegistrar, srv AbcsServer) {
	// If the following call panics, it indicates UnimplementedAbcsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Abcs_ServiceDesc, srv)
}

func _Abcs_GetAbc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAbcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbcsServer).GetAbc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abcs_GetAbc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbcsServer).GetAbc(ctx, req.(*GetAbcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Abcs_ServiceDesc is the grpc.ServiceDesc for Abcs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Abcs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrixhub.v1alpha1.Abcs",
	HandlerType: (*AbcsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAbc",
			Handler:    _Abcs_GetAbc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha1/abc.proto",
}
