// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/cleanup.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ExecuteCleanupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExecuteCleanupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecuteCleanupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecuteCleanupRequestMultiError, or nil if none found.
func (m *ExecuteCleanupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecuteCleanupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CleanOrphanedRepos

	// no validation rules for CleanOrphanedLfs

	// no validation rules for DryRun

	if d := m.GetGrace(); d != nil {
		dur, err := d.AsDuration(), d.CheckValid()
		if err != nil {
			err = ExecuteCleanupRequestValidationError{
				field:  "Grace",
				reason: "value is not a valid duration",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {

			gte := time.Duration(0*time.Second + 0*time.Nanosecond)

			if dur < gte {
				err := ExecuteCleanupRequestValidationError{
					field:  "Grace",
					reason: "value must be greater than or equal to 0s",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if m.GetMaxDeletes() < 0 {
		err := ExecuteCleanupRequestValidationError{
			field:  "MaxDeletes",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if d := m.GetBudget(); d != nil {
		dur, err := d.AsDuration(), d.CheckValid()
		if err != nil {
			err = ExecuteCleanupRequestValidationError{
				field:  "Budget",
				reason: "value is not a valid duration",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {

			gte := time.Duration(0*time.Second + 0*time.Nanosecond)

			if dur < gte {
				err := ExecuteCleanupRequestValidationError{
					field:  "Budget",
					reason: "value must be greater than or equal to 0s",
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}
	}

	if len(errors) > 0 {
		return ExecuteCleanupRequestMultiError(errors)
	}

	return nil
}

// ExecuteCleanupRequestMultiError is an error wrapping multiple validation
// errors returned by ExecuteCleanupRequest.ValidateAll() if the designated
// constraints aren't met.
type ExecuteCleanupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecuteCleanupRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecuteCleanupRequestMultiError) AllErrors() []error { return m }

// ExecuteCleanupRequestValidationError is the validation error returned by
// ExecuteCleanupRequest.Validate if the designated constraints aren't met.
type ExecuteCleanupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteCleanupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteCleanupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteCleanupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteCleanupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteCleanupRequestValidationError) ErrorName() string {
	return "ExecuteCleanupRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExecuteCleanupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteCleanupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteCleanupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteCleanupRequestValidationError{}

// Validate checks the field values on CleanupResult with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CleanupResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CleanupResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CleanupResultMultiError, or
// nil if none found.
func (m *CleanupResult) ValidateAll() error {
	return m.validate(true)
}

func (m *CleanupResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SpaceReclaimedBytes

	if all {
		switch v := interface{}(m.GetGc()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CleanupResultValidationError{
					field:  "Gc",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CleanupResultValidationError{
					field:  "Gc",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGc()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CleanupResultValidationError{
				field:  "Gc",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CleanupResultMultiError(errors)
	}

	return nil
}

// CleanupResultMultiError is an error wrapping multiple validation errors
// returned by CleanupResult.ValidateAll() if the designated constraints
// aren't met.
type CleanupResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CleanupResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CleanupResultMultiError) AllErrors() []error { return m }

// CleanupResultValidationError is the validation error returned by
// CleanupResult.Validate if the designated constraints aren't met.
type CleanupResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CleanupResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CleanupResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CleanupResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CleanupResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CleanupResultValidationError) ErrorName() string { return "CleanupResultValidationError" }

// Error satisfies the builtin error interface
func (e CleanupResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCleanupResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CleanupResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CleanupResultValidationError{}

// Validate checks the field values on GCResult with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GCResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GCResult with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GCResultMultiError, or nil
// if none found.
func (m *GCResult) ValidateAll() error {
	return m.validate(true)
}

func (m *GCResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DryRun

	// no validation rules for Repositories

	// no validation rules for DeletedGitObjects

	// no validation rules for DeletedGitBytes

	// no validation rules for GitReclaimedBytes

	// no validation rules for Failed

	// no validation rules for LiveObjects

	// no validation rules for PruneSkippedInGrace

	// no validation rules for SweptShards

	// no validation rules for SweptXorbs

	// no validation rules for XetReclaimedBytes

	// no validation rules for SweepSkippedInGrace

	if all {
		switch v := interface{}(m.GetSweepDone()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GCResultValidationError{
					field:  "SweepDone",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GCResultValidationError{
					field:  "SweepDone",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSweepDone()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GCResultValidationError{
				field:  "SweepDone",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for RemainingShards

	// no validation rules for RemainingXorbs

	if len(errors) > 0 {
		return GCResultMultiError(errors)
	}

	return nil
}

// GCResultMultiError is an error wrapping multiple validation errors returned
// by GCResult.ValidateAll() if the designated constraints aren't met.
type GCResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GCResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GCResultMultiError) AllErrors() []error { return m }

// GCResultValidationError is the validation error returned by
// GCResult.Validate if the designated constraints aren't met.
type GCResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GCResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GCResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GCResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GCResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GCResultValidationError) ErrorName() string { return "GCResultValidationError" }

// Error satisfies the builtin error interface
func (e GCResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGCResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GCResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GCResultValidationError{}

// Validate checks the field values on GetStorageStatsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetStorageStatsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetStorageStatsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetStorageStatsRequestMultiError, or nil if none found.
func (m *GetStorageStatsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetStorageStatsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetStorageStatsRequestMultiError(errors)
	}

	return nil
}

// GetStorageStatsRequestMultiError is an error wrapping multiple validation
// errors returned by GetStorageStatsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetStorageStatsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetStorageStatsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetStorageStatsRequestMultiError) AllErrors() []error { return m }

// GetStorageStatsRequestValidationError is the validation error returned by
// GetStorageStatsRequest.Validate if the designated constraints aren't met.
type GetStorageStatsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetStorageStatsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetStorageStatsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetStorageStatsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetStorageStatsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetStorageStatsRequestValidationError) ErrorName() string {
	return "GetStorageStatsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetStorageStatsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetStorageStatsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetStorageStatsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetStorageStatsRequestValidationError{}

// Validate checks the field values on StorageStats with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StorageStats) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StorageStats with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StorageStatsMultiError, or
// nil if none found.
func (m *StorageStats) ValidateAll() error {
	return m.validate(true)
}

func (m *StorageStats) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalSizeBytes

	if all {
		switch v := interface{}(m.GetGit()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StorageStatsValidationError{
					field:  "Git",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StorageStatsValidationError{
					field:  "Git",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGit()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StorageStatsValidationError{
				field:  "Git",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetXet()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StorageStatsValidationError{
					field:  "Xet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StorageStatsValidationError{
					field:  "Xet",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetXet()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StorageStatsValidationError{
				field:  "Xet",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return StorageStatsMultiError(errors)
	}

	return nil
}

// StorageStatsMultiError is an error wrapping multiple validation errors
// returned by StorageStats.ValidateAll() if the designated constraints aren't met.
type StorageStatsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StorageStatsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StorageStatsMultiError) AllErrors() []error { return m }

// StorageStatsValidationError is the validation error returned by
// StorageStats.Validate if the designated constraints aren't met.
type StorageStatsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StorageStatsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StorageStatsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StorageStatsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StorageStatsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StorageStatsValidationError) ErrorName() string { return "StorageStatsValidationError" }

// Error satisfies the builtin error interface
func (e StorageStatsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStorageStats.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StorageStatsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StorageStatsValidationError{}

// Validate checks the field values on StorageObjectUsage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StorageObjectUsage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StorageObjectUsage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StorageObjectUsageMultiError, or nil if none found.
func (m *StorageObjectUsage) ValidateAll() error {
	return m.validate(true)
}

func (m *StorageObjectUsage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Count

	// no validation rules for Bytes

	if len(errors) > 0 {
		return StorageObjectUsageMultiError(errors)
	}

	return nil
}

// StorageObjectUsageMultiError is an error wrapping multiple validation errors
// returned by StorageObjectUsage.ValidateAll() if the designated constraints
// aren't met.
type StorageObjectUsageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StorageObjectUsageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StorageObjectUsageMultiError) AllErrors() []error { return m }

// StorageObjectUsageValidationError is the validation error returned by
// StorageObjectUsage.Validate if the designated constraints aren't met.
type StorageObjectUsageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StorageObjectUsageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StorageObjectUsageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StorageObjectUsageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StorageObjectUsageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StorageObjectUsageValidationError) ErrorName() string {
	return "StorageObjectUsageValidationError"
}

// Error satisfies the builtin error interface
func (e StorageObjectUsageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStorageObjectUsage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StorageObjectUsageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StorageObjectUsageValidationError{}

// Validate checks the field values on GitStorageUsage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GitStorageUsage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GitStorageUsage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GitStorageUsageMultiError, or nil if none found.
func (m *GitStorageUsage) ValidateAll() error {
	return m.validate(true)
}

func (m *GitStorageUsage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetObjects()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GitStorageUsageValidationError{
					field:  "Objects",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GitStorageUsageValidationError{
					field:  "Objects",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetObjects()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GitStorageUsageValidationError{
				field:  "Objects",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOther()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GitStorageUsageValidationError{
					field:  "Other",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GitStorageUsageValidationError{
					field:  "Other",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOther()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GitStorageUsageValidationError{
				field:  "Other",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GitStorageUsageMultiError(errors)
	}

	return nil
}

// GitStorageUsageMultiError is an error wrapping multiple validation errors
// returned by GitStorageUsage.ValidateAll() if the designated constraints
// aren't met.
type GitStorageUsageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GitStorageUsageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GitStorageUsageMultiError) AllErrors() []error { return m }

// GitStorageUsageValidationError is the validation error returned by
// GitStorageUsage.Validate if the designated constraints aren't met.
type GitStorageUsageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GitStorageUsageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GitStorageUsageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GitStorageUsageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GitStorageUsageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GitStorageUsageValidationError) ErrorName() string { return "GitStorageUsageValidationError" }

// Error satisfies the builtin error interface
func (e GitStorageUsageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGitStorageUsage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GitStorageUsageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GitStorageUsageValidationError{}

// Validate checks the field values on XetStorageUsage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *XetStorageUsage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on XetStorageUsage with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// XetStorageUsageMultiError, or nil if none found.
func (m *XetStorageUsage) ValidateAll() error {
	return m.validate(true)
}

func (m *XetStorageUsage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetXorbs()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "Xorbs",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "Xorbs",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetXorbs()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return XetStorageUsageValidationError{
				field:  "Xorbs",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetShards()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "Shards",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "Shards",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetShards()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return XetStorageUsageValidationError{
				field:  "Shards",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetFileIndex()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "FileIndex",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "FileIndex",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFileIndex()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return XetStorageUsageValidationError{
				field:  "FileIndex",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetChunkIndex()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "ChunkIndex",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "ChunkIndex",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChunkIndex()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return XetStorageUsageValidationError{
				field:  "ChunkIndex",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSha256Index()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "Sha256Index",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, XetStorageUsageValidationError{
					field:  "Sha256Index",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSha256Index()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return XetStorageUsageValidationError{
				field:  "Sha256Index",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return XetStorageUsageMultiError(errors)
	}

	return nil
}

// XetStorageUsageMultiError is an error wrapping multiple validation errors
// returned by XetStorageUsage.ValidateAll() if the designated constraints
// aren't met.
type XetStorageUsageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m XetStorageUsageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m XetStorageUsageMultiError) AllErrors() []error { return m }

// XetStorageUsageValidationError is the validation error returned by
// XetStorageUsage.Validate if the designated constraints aren't met.
type XetStorageUsageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e XetStorageUsageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e XetStorageUsageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e XetStorageUsageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e XetStorageUsageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e XetStorageUsageValidationError) ErrorName() string { return "XetStorageUsageValidationError" }

// Error satisfies the builtin error interface
func (e XetStorageUsageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sXetStorageUsage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = XetStorageUsageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = XetStorageUsageValidationError{}
