// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/current_user.proto

package v1alpha1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessTokenStatus int32

const (
	AccessTokenStatus_ACCESS_TOKEN_STATUS_UNKNOWN AccessTokenStatus = 0
	AccessTokenStatus_ACCESS_TOKEN_STATUS_VALID   AccessTokenStatus = 1
	AccessTokenStatus_ACCESS_TOKEN_STATUS_EXPIRED AccessTokenStatus = 2
)

// Enum value maps for AccessTokenStatus.
var (
	AccessTokenStatus_name = map[int32]string{
		0: "ACCESS_TOKEN_STATUS_UNKNOWN",
		1: "ACCESS_TOKEN_STATUS_VALID",
		2: "ACCESS_TOKEN_STATUS_EXPIRED",
	}
	AccessTokenStatus_value = map[string]int32{
		"ACCESS_TOKEN_STATUS_UNKNOWN": 0,
		"ACCESS_TOKEN_STATUS_VALID":   1,
		"ACCESS_TOKEN_STATUS_EXPIRED": 2,
	}
)

func (x AccessTokenStatus) Enum() *AccessTokenStatus {
	p := new(AccessTokenStatus)
	*p = x
	return p
}

func (x AccessTokenStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessTokenStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_current_user_proto_enumTypes[0].Descriptor()
}

func (AccessTokenStatus) Type() protoreflect.EnumType {
	return &file_v1alpha1_current_user_proto_enumTypes[0]
}

func (x AccessTokenStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessTokenStatus.Descriptor instead.
func (AccessTokenStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{0}
}

type SSHKeyStatus int32

const (
	SSHKeyStatus_SSH_KEY_STATUS_UNKNOWN SSHKeyStatus = 0
	SSHKeyStatus_SSH_KEY_STATUS_VALID   SSHKeyStatus = 1
	SSHKeyStatus_SSH_KEY_STATUS_EXPIRED SSHKeyStatus = 2
)

// Enum value maps for SSHKeyStatus.
var (
	SSHKeyStatus_name = map[int32]string{
		0: "SSH_KEY_STATUS_UNKNOWN",
		1: "SSH_KEY_STATUS_VALID",
		2: "SSH_KEY_STATUS_EXPIRED",
	}
	SSHKeyStatus_value = map[string]int32{
		"SSH_KEY_STATUS_UNKNOWN": 0,
		"SSH_KEY_STATUS_VALID":   1,
		"SSH_KEY_STATUS_EXPIRED": 2,
	}
)

func (x SSHKeyStatus) Enum() *SSHKeyStatus {
	p := new(SSHKeyStatus)
	*p = x
	return p
}

func (x SSHKeyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSHKeyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_current_user_proto_enumTypes[1].Descriptor()
}

func (SSHKeyStatus) Type() protoreflect.EnumType {
	return &file_v1alpha1_current_user_proto_enumTypes[1]
}

func (x SSHKeyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SSHKeyStatus.Descriptor instead.
func (SSHKeyStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{1}
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{0}
}

func (x *ResetPasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{1}
}

type ListAccessTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessTokensRequest) Reset() {
	*x = ListAccessTokensRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessTokensRequest) ProtoMessage() {}

func (x *ListAccessTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessTokensRequest.ProtoReflect.Descriptor instead.
func (*ListAccessTokensRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{2}
}

type ListAccessTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AccessToken         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessTokensResponse) Reset() {
	*x = ListAccessTokensResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessTokensResponse) ProtoMessage() {}

func (x *ListAccessTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessTokensResponse.ProtoReflect.Descriptor instead.
func (*ListAccessTokensResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccessTokensResponse) GetItems() []*AccessToken {
	if x != nil {
		return x.Items
	}
	return nil
}

type AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        AccessTokenStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=matrixhub.v1alpha1.AccessTokenStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiredAt     string                 `protobuf:"bytes,5,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{4}
}

func (x *AccessToken) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccessToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessToken) GetStatus() AccessTokenStatus {
	if x != nil {
		return x.Status
	}
	return AccessTokenStatus_ACCESS_TOKEN_STATUS_UNKNOWN
}

func (x *AccessToken) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccessToken) GetExpiredAt() string {
	if x != nil {
		return x.ExpiredAt
	}
	return ""
}

type CreateAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessTokenRequest) Reset() {
	*x = CreateAccessTokenRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessTokenRequest) ProtoMessage() {}

func (x *CreateAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccessTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccessTokenRequest) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

type CreateAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessTokenResponse) Reset() {
	*x = CreateAccessTokenResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessTokenResponse) ProtoMessage() {}

func (x *CreateAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccessTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeleteAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccessTokenRequest) Reset() {
	*x = DeleteAccessTokenRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccessTokenRequest) ProtoMessage() {}

func (x *DeleteAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAccessTokenRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccessTokenResponse) Reset() {
	*x = DeleteAccessTokenResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccessTokenResponse) ProtoMessage() {}

func (x *DeleteAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{8}
}

type GetProjectRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRolesRequest) Reset() {
	*x = GetProjectRolesRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRolesRequest) ProtoMessage() {}

func (x *GetProjectRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRolesRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRolesRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{9}
}

type GetProjectRolesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ProjectRoles  map[string]ProjectRoleType `protobuf:"bytes,1,rep,name=project_roles,json=projectRoles,proto3" json:"project_roles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=matrixhub.v1alpha1.ProjectRoleType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRolesResponse) Reset() {
	*x = GetProjectRolesResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRolesResponse) ProtoMessage() {}

func (x *GetProjectRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRolesResponse.ProtoReflect.Descriptor instead.
func (*GetProjectRolesResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetProjectRolesResponse) GetProjectRoles() map[string]ProjectRoleType {
	if x != nil {
		return x.ProjectRoles
	}
	return nil
}

type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{11}
}

type GetCurrentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserResponse) Reset() {
	*x = GetCurrentUserResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserResponse) ProtoMessage() {}

func (x *GetCurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetCurrentUserResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCurrentUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetCurrentUserResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type CreateSSHKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSSHKeyRequest) Reset() {
	*x = CreateSSHKeyRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSSHKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSSHKeyRequest) ProtoMessage() {}

func (x *CreateSSHKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSSHKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateSSHKeyRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSSHKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSSHKeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateSSHKeyRequest) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

type CreateSSHKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSSHKeyResponse) Reset() {
	*x = CreateSSHKeyResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSSHKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSSHKeyResponse) ProtoMessage() {}

func (x *CreateSSHKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSSHKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateSSHKeyResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{14}
}

type DeleteSSHKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSSHKeyRequest) Reset() {
	*x = DeleteSSHKeyRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSSHKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSSHKeyRequest) ProtoMessage() {}

func (x *DeleteSSHKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSSHKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteSSHKeyRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSSHKeyRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSSHKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSSHKeyResponse) Reset() {
	*x = DeleteSSHKeyResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSSHKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSSHKeyResponse) ProtoMessage() {}

func (x *DeleteSSHKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSSHKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteSSHKeyResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{16}
}

type ListSSHKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSSHKeysRequest) Reset() {
	*x = ListSSHKeysRequest{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSSHKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSSHKeysRequest) ProtoMessage() {}

func (x *ListSSHKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSSHKeysRequest.ProtoReflect.Descriptor instead.
func (*ListSSHKeysRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{17}
}

type ListSSHKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SSHKey              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSSHKeysResponse) Reset() {
	*x = ListSSHKeysResponse{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSSHKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSSHKeysResponse) ProtoMessage() {}

func (x *ListSSHKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSSHKeysResponse.ProtoReflect.Descriptor instead.
func (*ListSSHKeysResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{18}
}

func (x *ListSSHKeysResponse) GetItems() []*SSHKey {
	if x != nil {
		return x.Items
	}
	return nil
}

type SSHKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        SSHKeyStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=matrixhub.v1alpha1.SSHKeyStatus" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKey) Reset() {
	*x = SSHKey{}
	mi := &file_v1alpha1_current_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKey) ProtoMessage() {}

func (x *SSHKey) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_current_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHKey.ProtoReflect.Descriptor instead.
func (*SSHKey) Descriptor() ([]byte, []int) {
	return file_v1alpha1_current_user_proto_rawDescGZIP(), []int{19}
}

func (x *SSHKey) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SSHKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SSHKey) GetStatus() SSHKeyStatus {
	if x != nil {
		return x.Status
	}
	return SSHKeyStatus_SSH_KEY_STATUS_UNKNOWN
}

func (x *SSHKey) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SSHKey) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

var File_v1alpha1_current_user_proto protoreflect.FileDescriptor

const file_v1alpha1_current_user_proto_rawDesc = "" +
	"\n" +
	"\x1bv1alpha1/current_user.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x13v1alpha1/role.proto\"n\n" +
	"\x14ResetPasswordRequest\x12*\n" +
	"\fold_password\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\voldPassword\x12*\n" +
	"\fnew_password\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vnewPassword\"\x17\n" +
	"\x15ResetPasswordResponse\"\x19\n" +
	"\x17ListAccessTokensRequest\"Q\n" +
	"\x18ListAccessTokensResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.matrixhub.v1alpha1.AccessTokenR\x05items\"\xae\x01\n" +
	"\vAccessToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12=\n" +
	"\x06status\x18\x03 \x01(\x0e2%.matrixhub.v1alpha1.AccessTokenStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x05 \x01(\tR\texpiredAt\"V\n" +
	"\x18CreateAccessTokenRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18}R\x04name\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\tR\bexpireAt\"1\n" +
	"\x19CreateAccessTokenResponse\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"*\n" +
	"\x18DeleteAccessTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x1b\n" +
	"\x19DeleteAccessTokenResponse\"\x18\n" +
	"\x16GetProjectRolesRequest\"\xe3\x01\n" +
	"\x17GetProjectRolesResponse\x12b\n" +
	"\rproject_roles\x18\x01 \x03(\v2=.matrixhub.v1alpha1.GetProjectRolesResponse.ProjectRolesEntryR\fprojectRoles\x1ad\n" +
	"\x11ProjectRolesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\x0e2#.matrixhub.v1alpha1.ProjectRoleTypeR\x05value:\x028\x01\"\x17\n" +
	"\x15GetCurrentUserRequest\"_\n" +
	"\x16GetCurrentUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\"w\n" +
	"\x13CreateSSHKeyRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tpublicKey\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\tR\bexpireAt\"\x16\n" +
	"\x14CreateSSHKeyResponse\"%\n" +
	"\x13DeleteSSHKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x16\n" +
	"\x14DeleteSSHKeyResponse\"\x14\n" +
	"\x12ListSSHKeysRequest\"G\n" +
	"\x13ListSSHKeysResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.matrixhub.v1alpha1.SSHKeyR\x05items\"\xa2\x01\n" +
	"\x06SSHKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .matrixhub.v1alpha1.SSHKeyStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\texpire_at\x18\x05 \x01(\tR\bexpireAt*t\n" +
	"\x11AccessTokenStatus\x12\x1f\n" +
	"\x1bACCESS_TOKEN_STATUS_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19ACCESS_TOKEN_STATUS_VALID\x10\x01\x12\x1f\n" +
	"\x1bACCESS_TOKEN_STATUS_EXPIRED\x10\x02*`\n" +
	"\fSSHKeyStatus\x12\x1a\n" +
	"\x16SSH_KEY_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14SSH_KEY_STATUS_VALID\x10\x01\x12\x1a\n" +
	"\x16SSH_KEY_STATUS_EXPIRED\x10\x022\x83\v\n" +
	"\vCurrentUser\x12\x8b\x01\n" +
	"\x0eGetCurrentUser\x12).matrixhub.v1alpha1.GetCurrentUserRequest\x1a*.matrixhub.v1alpha1.GetCurrentUserResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1alpha1/current-user\x12\x9a\x01\n" +
	"\rResetPassword\x12(.matrixhub.v1alpha1.ResetPasswordRequest\x1a).matrixhub.v1alpha1.ResetPasswordResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1alpha1/current-user/reset-password\x12\x9f\x01\n" +
	"\x10ListAccessTokens\x12+.matrixhub.v1alpha1.ListAccessTokensRequest\x1a,.matrixhub.v1alpha1.ListAccessTokensResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1alpha1/current-user/access-tokens\x12\xa5\x01\n" +
	"\x11CreateAccessToken\x12,.matrixhub.v1alpha1.CreateAccessTokenRequest\x1a-.matrixhub.v1alpha1.CreateAccessTokenResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/api/v1alpha1/current-user/access-tokens\x12\xa7\x01\n" +
	"\x11DeleteAccessToken\x12,.matrixhub.v1alpha1.DeleteAccessTokenRequest\x1a-.matrixhub.v1alpha1.DeleteAccessTokenResponse\"5\x82\xd3\xe4\x93\x02/*-/api/v1alpha1/current-user/access-tokens/{id}\x12\x9c\x01\n" +
	"\x0fGetProjectRoles\x12*.matrixhub.v1alpha1.GetProjectRolesRequest\x1a+.matrixhub.v1alpha1.GetProjectRolesResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1alpha1/current-user/projects/role\x12\x91\x01\n" +
	"\fCreateSSHKey\x12'.matrixhub.v1alpha1.CreateSSHKeyRequest\x1a(.matrixhub.v1alpha1.CreateSSHKeyResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1alpha1/current-user/ssh-keys\x12\x93\x01\n" +
	"\fDeleteSSHKey\x12'.matrixhub.v1alpha1.DeleteSSHKeyRequest\x1a(.matrixhub.v1alpha1.DeleteSSHKeyResponse\"0\x82\xd3\xe4\x93\x02**(/api/v1alpha1/current-user/ssh-keys/{id}\x12\x8b\x01\n" +
	"\vListSSHKeys\x12&.matrixhub.v1alpha1.ListSSHKeysRequest\x1a'.matrixhub.v1alpha1.ListSSHKeysResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1alpha1/current-user/ssh-keysB<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_current_user_proto_rawDescOnce sync.Once
	file_v1alpha1_current_user_proto_rawDescData []byte
)

func file_v1alpha1_current_user_proto_rawDescGZIP() []byte {
	file_v1alpha1_current_user_proto_rawDescOnce.Do(func() {
		file_v1alpha1_current_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_current_user_proto_rawDesc), len(file_v1alpha1_current_user_proto_rawDesc)))
	})
	return file_v1alpha1_current_user_proto_rawDescData
}

var file_v1alpha1_current_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1alpha1_current_user_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1alpha1_current_user_proto_goTypes = []any{
	(AccessTokenStatus)(0),            // 0: matrixhub.v1alpha1.AccessTokenStatus
	(SSHKeyStatus)(0),                 // 1: matrixhub.v1alpha1.SSHKeyStatus
	(*ResetPasswordRequest)(nil),      // 2: matrixhub.v1alpha1.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),     // 3: matrixhub.v1alpha1.ResetPasswordResponse
	(*ListAccessTokensRequest)(nil),   // 4: matrixhub.v1alpha1.ListAccessTokensRequest
	(*ListAccessTokensResponse)(nil),  // 5: matrixhub.v1alpha1.ListAccessTokensResponse
	(*AccessToken)(nil),               // 6: matrixhub.v1alpha1.AccessToken
	(*CreateAccessTokenRequest)(nil),  // 7: matrixhub.v1alpha1.CreateAccessTokenRequest
	(*CreateAccessTokenResponse)(nil), // 8: matrixhub.v1alpha1.CreateAccessTokenResponse
	(*DeleteAccessTokenRequest)(nil),  // 9: matrixhub.v1alpha1.DeleteAccessTokenRequest
	(*DeleteAccessTokenResponse)(nil), // 10: matrixhub.v1alpha1.DeleteAccessTokenResponse
	(*GetProjectRolesRequest)(nil),    // 11: matrixhub.v1alpha1.GetProjectRolesRequest
	(*GetProjectRolesResponse)(nil),   // 12: matrixhub.v1alpha1.GetProjectRolesResponse
	(*GetCurrentUserRequest)(nil),     // 13: matrixhub.v1alpha1.GetCurrentUserRequest
	(*GetCurrentUserResponse)(nil),    // 14: matrixhub.v1alpha1.GetCurrentUserResponse
	(*CreateSSHKeyRequest)(nil),       // 15: matrixhub.v1alpha1.CreateSSHKeyRequest
	(*CreateSSHKeyResponse)(nil),      // 16: matrixhub.v1alpha1.CreateSSHKeyResponse
	(*DeleteSSHKeyRequest)(nil),       // 17: matrixhub.v1alpha1.DeleteSSHKeyRequest
	(*DeleteSSHKeyResponse)(nil),      // 18: matrixhub.v1alpha1.DeleteSSHKeyResponse
	(*ListSSHKeysRequest)(nil),        // 19: matrixhub.v1alpha1.ListSSHKeysRequest
	(*ListSSHKeysResponse)(nil),       // 20: matrixhub.v1alpha1.ListSSHKeysResponse
	(*SSHKey)(nil),                    // 21: matrixhub.v1alpha1.SSHKey
	nil,                               // 22: matrixhub.v1alpha1.GetProjectRolesResponse.ProjectRolesEntry
	(ProjectRoleType)(0),              // 23: matrixhub.v1alpha1.ProjectRoleType
}
var file_v1alpha1_current_user_proto_depIdxs = []int32{
	6,  // 0: matrixhub.v1alpha1.ListAccessTokensResponse.items:type_name -> matrixhub.v1alpha1.AccessToken
	0,  // 1: matrixhub.v1alpha1.AccessToken.status:type_name -> matrixhub.v1alpha1.AccessTokenStatus
	22, // 2: matrixhub.v1alpha1.GetProjectRolesResponse.project_roles:type_name -> matrixhub.v1alpha1.GetProjectRolesResponse.ProjectRolesEntry
	21, // 3: matrixhub.v1alpha1.ListSSHKeysResponse.items:type_name -> matrixhub.v1alpha1.SSHKey
	1,  // 4: matrixhub.v1alpha1.SSHKey.status:type_name -> matrixhub.v1alpha1.SSHKeyStatus
	23, // 5: matrixhub.v1alpha1.GetProjectRolesResponse.ProjectRolesEntry.value:type_name -> matrixhub.v1alpha1.ProjectRoleType
	13, // 6: matrixhub.v1alpha1.CurrentUser.GetCurrentUser:input_type -> matrixhub.v1alpha1.GetCurrentUserRequest
	2,  // 7: matrixhub.v1alpha1.CurrentUser.ResetPassword:input_type -> matrixhub.v1alpha1.ResetPasswordRequest
	4,  // 8: matrixhub.v1alpha1.CurrentUser.ListAccessTokens:input_type -> matrixhub.v1alpha1.ListAccessTokensRequest
	7,  // 9: matrixhub.v1alpha1.CurrentUser.CreateAccessToken:input_type -> matrixhub.v1alpha1.CreateAccessTokenRequest
	9,  // 10: matrixhub.v1alpha1.CurrentUser.DeleteAccessToken:input_type -> matrixhub.v1alpha1.DeleteAccessTokenRequest
	11, // 11: matrixhub.v1alpha1.CurrentUser.GetProjectRoles:input_type -> matrixhub.v1alpha1.GetProjectRolesRequest
	15, // 12: matrixhub.v1alpha1.CurrentUser.CreateSSHKey:input_type -> matrixhub.v1alpha1.CreateSSHKeyRequest
	17, // 13: matrixhub.v1alpha1.CurrentUser.DeleteSSHKey:input_type -> matrixhub.v1alpha1.DeleteSSHKeyRequest
	19, // 14: matrixhub.v1alpha1.CurrentUser.ListSSHKeys:input_type -> matrixhub.v1alpha1.ListSSHKeysRequest
	14, // 15: matrixhub.v1alpha1.CurrentUser.GetCurrentUser:output_type -> matrixhub.v1alpha1.GetCurrentUserResponse
	3,  // 16: matrixhub.v1alpha1.CurrentUser.ResetPassword:output_type -> matrixhub.v1alpha1.ResetPasswordResponse
	5,  // 17: matrixhub.v1alpha1.CurrentUser.ListAccessTokens:output_type -> matrixhub.v1alpha1.ListAccessTokensResponse
	8,  // 18: matrixhub.v1alpha1.CurrentUser.CreateAccessToken:output_type -> matrixhub.v1alpha1.CreateAccessTokenResponse
	10, // 19: matrixhub.v1alpha1.CurrentUser.DeleteAccessToken:output_type -> matrixhub.v1alpha1.DeleteAccessTokenResponse
	12, // 20: matrixhub.v1alpha1.CurrentUser.GetProjectRoles:output_type -> matrixhub.v1alpha1.GetProjectRolesResponse
	16, // 21: matrixhub.v1alpha1.CurrentUser.CreateSSHKey:output_type -> matrixhub.v1alpha1.CreateSSHKeyResponse
	18, // 22: matrixhub.v1alpha1.CurrentUser.DeleteSSHKey:output_type -> matrixhub.v1alpha1.DeleteSSHKeyResponse
	20, // 23: matrixhub.v1alpha1.CurrentUser.ListSSHKeys:output_type -> matrixhub.v1alpha1.ListSSHKeysResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1alpha1_current_user_proto_init() }
func file_v1alpha1_current_user_proto_init() {
	if File_v1alpha1_current_user_proto != nil {
		return
	}
	file_v1alpha1_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_current_user_proto_rawDesc), len(file_v1alpha1_current_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_current_user_proto_goTypes,
		DependencyIndexes: file_v1alpha1_current_user_proto_depIdxs,
		EnumInfos:         file_v1alpha1_current_user_proto_enumTypes,
		MessageInfos:      file_v1alpha1_current_user_proto_msgTypes,
	}.Build()
	File_v1alpha1_current_user_proto = out.File
	file_v1alpha1_current_user_proto_goTypes = nil
	file_v1alpha1_current_user_proto_depIdxs = nil
}
