// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/hf_compat.proto

package v1alpha1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CLILoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLILoginRequest) Reset() {
	*x = CLILoginRequest{}
	mi := &file_v1alpha1_hf_compat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLILoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLILoginRequest) ProtoMessage() {}

func (x *CLILoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_hf_compat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLILoginRequest.ProtoReflect.Descriptor instead.
func (*CLILoginRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_hf_compat_proto_rawDescGZIP(), []int{0}
}

type CLILoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLILoginResponse) Reset() {
	*x = CLILoginResponse{}
	mi := &file_v1alpha1_hf_compat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLILoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLILoginResponse) ProtoMessage() {}

func (x *CLILoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_hf_compat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLILoginResponse.ProtoReflect.Descriptor instead.
func (*CLILoginResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_hf_compat_proto_rawDescGZIP(), []int{1}
}

var File_v1alpha1_hf_compat_proto protoreflect.FileDescriptor

const file_v1alpha1_hf_compat_proto_rawDesc = "" +
	"\n" +
	"\x18v1alpha1/hf_compat.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fCLILoginRequest\"\x12\n" +
	"\x10CLILoginResponse2\x80\x01\n" +
	"\x0fHfCompatibility\x12m\n" +
	"\bCLILogin\x12#.matrixhub.v1alpha1.CLILoginRequest\x1a$.matrixhub.v1alpha1.CLILoginResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/whoami-v2B<Z:github.com/matrixhub-ai/matrixhub/api/go/v1alpha1;v1alpha1b\x06proto3"

var (
	file_v1alpha1_hf_compat_proto_rawDescOnce sync.Once
	file_v1alpha1_hf_compat_proto_rawDescData []byte
)

func file_v1alpha1_hf_compat_proto_rawDescGZIP() []byte {
	file_v1alpha1_hf_compat_proto_rawDescOnce.Do(func() {
		file_v1alpha1_hf_compat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_hf_compat_proto_rawDesc), len(file_v1alpha1_hf_compat_proto_rawDesc)))
	})
	return file_v1alpha1_hf_compat_proto_rawDescData
}

var file_v1alpha1_hf_compat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1alpha1_hf_compat_proto_goTypes = []any{
	(*CLILoginRequest)(nil),  // 0: matrixhub.v1alpha1.CLILoginRequest
	(*CLILoginResponse)(nil), // 1: matrixhub.v1alpha1.CLILoginResponse
}
var file_v1alpha1_hf_compat_proto_depIdxs = []int32{
	0, // 0: matrixhub.v1alpha1.HfCompatibility.CLILogin:input_type -> matrixhub.v1alpha1.CLILoginRequest
	1, // 1: matrixhub.v1alpha1.HfCompatibility.CLILogin:output_type -> matrixhub.v1alpha1.CLILoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1alpha1_hf_compat_proto_init() }
func file_v1alpha1_hf_compat_proto_init() {
	if File_v1alpha1_hf_compat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_hf_compat_proto_rawDesc), len(file_v1alpha1_hf_compat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_hf_compat_proto_goTypes,
		DependencyIndexes: file_v1alpha1_hf_compat_proto_depIdxs,
		MessageInfos:      file_v1alpha1_hf_compat_proto_msgTypes,
	}.Build()
	File_v1alpha1_hf_compat_proto = out.File
	file_v1alpha1_hf_compat_proto_goTypes = nil
	file_v1alpha1_hf_compat_proto_depIdxs = nil
}
