// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: v1alpha1/hf_compat.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HfCompatibility_CLILogin_FullMethodName = "/matrixhub.v1alpha1.HfCompatibility/CLILogin"
)

// HfCompatibilityClient is the client API for HfCompatibility service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HfCompatibilityClient interface {
	CLILogin(ctx context.Context, in *CLILoginRequest, opts ...grpc.CallOption) (*CLILoginResponse, error)
}

type hfCompatibilityClient struct {
	cc grpc.ClientConnInterface
}

func NewHfCompatibilityClient(cc grpc.ClientConnInterface) HfCompatibilityClient {
	return &hfCompatibilityClient{cc}
}

func (c *hfCompatibilityClient) CLILogin(ctx context.Context, in *CLILoginRequest, opts ...grpc.CallOption) (*CLILoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CLILoginResponse)
	err := c.cc.Invoke(ctx, HfCompatibility_CLILogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HfCompatibilityServer is the server API for HfCompatibility service.
// All implementations should embed UnimplementedHfCompatibilityServer
// for forward compatibility.
type HfCompatibilityServer interface {
	CLILogin(context.Context, *CLILoginRequest) (*CLILoginResponse, error)
}

// UnimplementedHfCompatibilityServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHfCompatibilityServer struct{}

func (UnimplementedHfCompatibilityServer) CLILogin(context.Context, *CLILoginRequest) (*CLILoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CLILogin not implemented")
}
func (UnimplementedHfCompatibilityServer) testEmbeddedByValue() {}

// UnsafeHfCompatibilityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HfCompatibilityServer will
// result in compilation errors.
type UnsafeHfCompatibilityServer interface {
	mustEmbedUnimplementedHfCompatibilityServer()
}

func RegisterHfCompatibilityServer(s grpc.ServiceRegistrar, srv HfCompatibilityServer) {
	// If the following call panics, it indicates UnimplementedHfCompatibilityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HfCompatibility_ServiceDesc, srv)
}

func _HfCompatibility_CLILogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLILoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HfCompatibilityServer).CLILogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HfCompatibility_CLILogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HfCompatibilityServer).CLILogin(ctx, req.(*CLILoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HfCompatibility_ServiceDesc is the grpc.ServiceDesc for HfCompatibility service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HfCompatibility_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrixhub.v1alpha1.HfCompatibility",
	HandlerType: (*HfCompatibilityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CLILogin",
			Handler:    _HfCompatibility_CLILogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha1/hf_compat.proto",
}
