// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1alpha1/hf_compat.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CLILoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CLILoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CLILoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CLILoginRequestMultiError, or nil if none found.
func (m *CLILoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CLILoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CLILoginRequestMultiError(errors)
	}

	return nil
}

// CLILoginRequestMultiError is an error wrapping multiple validation errors
// returned by CLILoginRequest.ValidateAll() if the designated constraints
// aren't met.
type CLILoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CLILoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CLILoginRequestMultiError) AllErrors() []error { return m }

// CLILoginRequestValidationError is the validation error returned by
// CLILoginRequest.Validate if the designated constraints aren't met.
type CLILoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CLILoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CLILoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CLILoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CLILoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CLILoginRequestValidationError) ErrorName() string { return "CLILoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e CLILoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCLILoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CLILoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CLILoginRequestValidationError{}

// Validate checks the field values on CLILoginResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CLILoginResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CLILoginResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CLILoginResponseMultiError, or nil if none found.
func (m *CLILoginResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CLILoginResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CLILoginResponseMultiError(errors)
	}

	return nil
}

// CLILoginResponseMultiError is an error wrapping multiple validation errors
// returned by CLILoginResponse.ValidateAll() if the designated constraints
// aren't met.
type CLILoginResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CLILoginResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CLILoginResponseMultiError) AllErrors() []error { return m }

// CLILoginResponseValidationError is the validation error returned by
// CLILoginResponse.Validate if the designated constraints aren't met.
type CLILoginResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CLILoginResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CLILoginResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CLILoginResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CLILoginResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CLILoginResponseValidationError) ErrorName() string { return "CLILoginResponseValidationError" }

// Error satisfies the builtin error interface
func (e CLILoginResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCLILoginResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CLILoginResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CLILoginResponseValidationError{}
