// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: v1alpha1/project.proto

package v1alpha1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProjectItem is the project item.
type ProjectItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the project.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// display_name is the display name of the project.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description is the description of the project.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectItem) Reset() {
	*x = ProjectItem{}
	mi := &file_v1alpha1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectItem) ProtoMessage() {}

func (x *ProjectItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectItem.ProtoReflect.Descriptor instead.
func (*ProjectItem) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectItem) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProjectItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the project.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// display_name is the display name of the project.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// description is the description of the project.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// GetProjectRequest is the request message for GetProject.
type GetProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name of the project.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListProjectsRequest is the request message for ListProjects.
type ListProjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// limit is the maximum number of projects to return.
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// cursor is the pagination cursor.
	Cursor string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// order_by specifies the ordering of the projects.
	// It is a list of fields to order by, each prefixed by "+" (ascending) or "-" (descending).
	// For example, to order by name ascending and created_at descending:
	//
	//	order_by: ["+name", "-created_at"]
	OrderBy       []string `protobuf:"bytes,3,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_v1alpha1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProjectsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListProjectsRequest) GetOrderBy() []string {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

type ListProjects struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// items is the list of projects.
	Items []*ProjectItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// count is the total number of projects.
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// next_cursor is the cursor for the next page.
	// If there are no more pages, this field will be empty.
	NextCursor    string `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjects) Reset() {
	*x = ListProjects{}
	mi := &file_v1alpha1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjects) ProtoMessage() {}

func (x *ListProjects) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjects.ProtoReflect.Descriptor instead.
func (*ListProjects) Descriptor() ([]byte, []int) {
	return file_v1alpha1_project_proto_rawDescGZIP(), []int{4}
}

func (x *ListProjects) GetItems() []*ProjectItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProjects) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListProjects) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_v1alpha1_project_proto protoreflect.FileDescriptor

const file_v1alpha1_project_proto_rawDesc = "" +
	"\n" +
	"\x16v1alpha1/project.proto\x12\x12matrixhub.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"f\n" +
	"\vProjectItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8c\x01\n" +
	"\x14CreateProjectRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18?R\x04name\x12*\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x18?R\vdisplayName\x12)\n" +
	"\vdescription\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18?R\vdescription\"'\n" +
	"\x11GetProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"^\n" +
	"\x13ListProjectsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x19\n" +
	"\border_by\x18\x03 \x03(\tR\aorderBy\"|\n" +
	"\fListProjects\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.matrixhub.v1alpha1.ProjectItemR\x05items\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor2\xf2\x02\n" +
	"\bProjects\x12t\n" +
	"\x03Get\x12%.matrixhub.v1alpha1.GetProjectRequest\x1a\x1f.matrixhub.v1alpha1.ProjectItem\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1alpha1/projects/{name}\x12}\n" +
	"\x06Create\x12(.matrixhub.v1alpha1.CreateProjectRequest\x1a\x1f.matrixhub.v1alpha1.ProjectItem\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1alpha1/projects/{name}\x12q\n" +
	"\x04List\x12'.matrixhub.v1alpha1.ListProjectsRequest\x1a .matrixhub.v1alpha1.ListProjects\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1alpha1/projectsBDZBgithub.com/matrixhub-ai/matrixhub/api/go/v1alpha1/project;v1alpha1b\x06proto3"

var (
	file_v1alpha1_project_proto_rawDescOnce sync.Once
	file_v1alpha1_project_proto_rawDescData []byte
)

func file_v1alpha1_project_proto_rawDescGZIP() []byte {
	file_v1alpha1_project_proto_rawDescOnce.Do(func() {
		file_v1alpha1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1alpha1_project_proto_rawDesc), len(file_v1alpha1_project_proto_rawDesc)))
	})
	return file_v1alpha1_project_proto_rawDescData
}

var file_v1alpha1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1alpha1_project_proto_goTypes = []any{
	(*ProjectItem)(nil),          // 0: matrixhub.v1alpha1.ProjectItem
	(*CreateProjectRequest)(nil), // 1: matrixhub.v1alpha1.CreateProjectRequest
	(*GetProjectRequest)(nil),    // 2: matrixhub.v1alpha1.GetProjectRequest
	(*ListProjectsRequest)(nil),  // 3: matrixhub.v1alpha1.ListProjectsRequest
	(*ListProjects)(nil),         // 4: matrixhub.v1alpha1.ListProjects
}
var file_v1alpha1_project_proto_depIdxs = []int32{
	0, // 0: matrixhub.v1alpha1.ListProjects.items:type_name -> matrixhub.v1alpha1.ProjectItem
	2, // 1: matrixhub.v1alpha1.Projects.Get:input_type -> matrixhub.v1alpha1.GetProjectRequest
	1, // 2: matrixhub.v1alpha1.Projects.Create:input_type -> matrixhub.v1alpha1.CreateProjectRequest
	3, // 3: matrixhub.v1alpha1.Projects.List:input_type -> matrixhub.v1alpha1.ListProjectsRequest
	0, // 4: matrixhub.v1alpha1.Projects.Get:output_type -> matrixhub.v1alpha1.ProjectItem
	0, // 5: matrixhub.v1alpha1.Projects.Create:output_type -> matrixhub.v1alpha1.ProjectItem
	4, // 6: matrixhub.v1alpha1.Projects.List:output_type -> matrixhub.v1alpha1.ListProjects
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1alpha1_project_proto_init() }
func file_v1alpha1_project_proto_init() {
	if File_v1alpha1_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1alpha1_project_proto_rawDesc), len(file_v1alpha1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1alpha1_project_proto_goTypes,
		DependencyIndexes: file_v1alpha1_project_proto_depIdxs,
		MessageInfos:      file_v1alpha1_project_proto_msgTypes,
	}.Build()
	File_v1alpha1_project_proto = out.File
	file_v1alpha1_project_proto_goTypes = nil
	file_v1alpha1_project_proto_depIdxs = nil
}
