// Code generated by MockGen. DO NOT EDIT.
// Source: registry.go
//
// Generated by this command:
//
//	mockgen -source=registry.go -destination=mocks/registry_repo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	registry "github.com/matrixhub-ai/matrixhub/internal/domain/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockIRegistryRepo is a mock of IRegistryRepo interface.
type MockIRegistryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRegistryRepoMockRecorder
	isgomock struct{}
}

// MockIRegistryRepoMockRecorder is the mock recorder for MockIRegistryRepo.
type MockIRegistryRepoMockRecorder struct {
	mock *MockIRegistryRepo
}

// NewMockIRegistryRepo creates a new mock instance.
func NewMockIRegistryRepo(ctrl *gomock.Controller) *MockIRegistryRepo {
	mock := &MockIRegistryRepo{ctrl: ctrl}
	mock.recorder = &MockIRegistryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRegistryRepo) EXPECT() *MockIRegistryRepoMockRecorder {
	return m.recorder
}

// CreateRegistry mocks base method.
func (m *MockIRegistryRepo) CreateRegistry(ctx context.Context, arg1 registry.Registry) (*registry.Registry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRegistry", ctx, arg1)
	ret0, _ := ret[0].(*registry.Registry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRegistry indicates an expected call of CreateRegistry.
func (mr *MockIRegistryRepoMockRecorder) CreateRegistry(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRegistry", reflect.TypeOf((*MockIRegistryRepo)(nil).CreateRegistry), ctx, arg1)
}

// DeleteRegistry mocks base method.
func (m *MockIRegistryRepo) DeleteRegistry(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegistry", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegistry indicates an expected call of DeleteRegistry.
func (mr *MockIRegistryRepoMockRecorder) DeleteRegistry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegistry", reflect.TypeOf((*MockIRegistryRepo)(nil).DeleteRegistry), ctx, id)
}

// GetRegistry mocks base method.
func (m *MockIRegistryRepo) GetRegistry(ctx context.Context, id int) (*registry.Registry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistry", ctx, id)
	ret0, _ := ret[0].(*registry.Registry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistry indicates an expected call of GetRegistry.
func (mr *MockIRegistryRepoMockRecorder) GetRegistry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistry", reflect.TypeOf((*MockIRegistryRepo)(nil).GetRegistry), ctx, id)
}

// ListRegistries mocks base method.
func (m *MockIRegistryRepo) ListRegistries(ctx context.Context, page, pageSize int, search string) ([]*registry.Registry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegistries", ctx, page, pageSize, search)
	ret0, _ := ret[0].([]*registry.Registry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRegistries indicates an expected call of ListRegistries.
func (mr *MockIRegistryRepoMockRecorder) ListRegistries(ctx, page, pageSize, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegistries", reflect.TypeOf((*MockIRegistryRepo)(nil).ListRegistries), ctx, page, pageSize, search)
}

// PingRegistry mocks base method.
func (m *MockIRegistryRepo) PingRegistry(ctx context.Context, reg registry.Registry) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingRegistry", ctx, reg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PingRegistry indicates an expected call of PingRegistry.
func (mr *MockIRegistryRepoMockRecorder) PingRegistry(ctx, reg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingRegistry", reflect.TypeOf((*MockIRegistryRepo)(nil).PingRegistry), ctx, reg)
}

// UpdateRegistry mocks base method.
func (m *MockIRegistryRepo) UpdateRegistry(ctx context.Context, arg1 registry.Registry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRegistry", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRegistry indicates an expected call of UpdateRegistry.
func (mr *MockIRegistryRepoMockRecorder) UpdateRegistry(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRegistry", reflect.TypeOf((*MockIRegistryRepo)(nil).UpdateRegistry), ctx, arg1)
}

// GetRegistryByName mocks base method.
func (m *MockIRegistryRepo) GetRegistryByName(ctx context.Context, name string) (*registry.Registry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistryByName", ctx, name)
	ret0, _ := ret[0].(*registry.Registry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistryByName indicates an expected call of GetRegistryByName.
func (mr *MockIRegistryRepoMockRecorder) GetRegistryByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistryByName", reflect.TypeOf((*MockIRegistryRepo)(nil).GetRegistryByName), ctx, name)
}
