/*
 * v1alpha1/registry.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1RegistryStatus string

// List of v1alpha1RegistryStatus
const (
	UNSPECIFIED_V1alpha1RegistryStatus V1alpha1RegistryStatus = "REGISTRY_STATUS_UNSPECIFIED"
	HEALTHY_V1alpha1RegistryStatus V1alpha1RegistryStatus = "REGISTRY_STATUS_HEALTHY"
	UNHEALTHY_V1alpha1RegistryStatus V1alpha1RegistryStatus = "REGISTRY_STATUS_UNHEALTHY"
)
