/*
 * v1alpha1/registry.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1ListRegistriesResponse struct {
	// List of registries matching the request.
	Registries []V1alpha1Registry `json:"registries,omitempty"`
	// Pagination metadata for the result set.
	Pagination *V1alpha1Pagination `json:"pagination,omitempty"`
}
