/*
 * v1alpha1/registry.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type V1alpha1UpdateRegistryResponse struct {
	// The updated registry.
	Registry *V1alpha1Registry `json:"registry,omitempty"`
}
