/*
 * v1alpha1/registry.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type RegistriesUpdateRegistryBody struct {
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Url string `json:"url,omitempty"`
	// Basic authentication credentials for the registry.
	Basic *V1alpha1RegistryBasicCredential `json:"basic,omitempty"`
	Insecure bool `json:"insecure,omitempty"`
}
