// Code generated by MockGen. DO NOT EDIT.
// Source: preset.go
//
// Generated by this command:
//
//	mockgen -source=preset.go -destination=mocks/preset_repo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	preset "github.com/matrixhub-ai/matrixhub/internal/domain/preset"
	gomock "go.uber.org/mock/gomock"
)

// MockIPresetRepo is a mock of IPresetRepo interface.
type MockIPresetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIPresetRepoMockRecorder
	isgomock struct{}
}

// MockIPresetRepoMockRecorder is the mock recorder for MockIPresetRepo.
type MockIPresetRepoMockRecorder struct {
	mock *MockIPresetRepo
}

// NewMockIPresetRepo creates a new mock instance.
func NewMockIPresetRepo(ctrl *gomock.Controller) *MockIPresetRepo {
	mock := &MockIPresetRepo{ctrl: ctrl}
	mock.recorder = &MockIPresetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPresetRepo) EXPECT() *MockIPresetRepoMockRecorder {
	return m.recorder
}

// SeedIfEmpty mocks base method.
func (m *MockIPresetRepo) SeedIfEmpty(ctx context.Context, manifest *preset.Manifest) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeedIfEmpty", ctx, manifest)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SeedIfEmpty indicates an expected call of SeedIfEmpty.
func (mr *MockIPresetRepoMockRecorder) SeedIfEmpty(ctx, manifest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeedIfEmpty", reflect.TypeOf((*MockIPresetRepo)(nil).SeedIfEmpty), ctx, manifest)
}
