import {
  Box, Code, Skeleton,
} from '@mantine/core'
import {
  useEffect, useRef, useState,
} from 'react'

import { CopyValueButton } from '@/shared/components/CopyValueButton'
import { highlightCode } from '@/shared/utils/shiki'

import classes from './ShikiCodeBlock.module.css'

interface ShikiCodeBlockProps {
  code: string
  lang: string
  /** Copy button in the top-right corner. Defaults to true. */
  copyable?: boolean
}

/**
 * Syntax-highlighted, copyable code block. Renders a plain `<Code>` while
 * Shiki (and the requested grammar) loads, then swaps in the highlighted HTML.
 */
export function ShikiCodeBlock({
  code,
  lang,
  copyable = true,
}: ShikiCodeBlockProps) {
  const [highlighted, setHighlighted] = useState<{
    code: string
    html: string
  } | null>(null)

  useEffect(() => {
    let cancelled = false

    highlightCode(code, lang).then(
      html => !cancelled && setHighlighted({
        code,
        html,
      }),
      () => !cancelled && setHighlighted({
        code,
        html: '',
      }),
    )

    return () => {
      cancelled = true
    }
  }, [code, lang])

  const isReady = highlighted?.code === code
  const rootRef = useRef<HTMLDivElement>(null)

  // Mirror the <pre>'s theme background variables onto the root so the copy
  // button can match the code surface in either colour scheme.
  useEffect(() => {
    const root = rootRef.current
    const pre = root?.querySelector('pre')

    if (!root || !pre) {
      return
    }

    for (const name of ['--shiki-light-bg', '--shiki-dark-bg']) {
      root.style.setProperty(name, pre.style.getPropertyValue(name))
    }
  }, [highlighted])

  return (
    <Box ref={rootRef} className={classes.root}>
      {copyable && (
        <Box className={classes.copyButton}>
          <CopyValueButton value={code} />
        </Box>
      )}

      {!isReady && (
        <Skeleton radius="sm">
          <Code block className={classes.fallback}>{code}</Code>
        </Skeleton>
      )}

      {isReady && !highlighted.html && (
        <Code block className={classes.fallback}>{code}</Code>
      )}

      {isReady && highlighted.html && (
        <Box
          className={classes.shiki}
          // eslint-disable-next-line @eslint-react/dom/no-dangerously-set-innerhtml -- html is generated by Shiki from our own snippet, not from user content
          dangerouslySetInnerHTML={{ __html: highlighted.html }}
        />
      )}
    </Box>
  )
}
